package net.minestom.server.world.timeline;

import net.minestom.server.registry.RegistryKey;

/**
 * This class contains all the generated constants for {@link Timeline}
 * <br>
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
sealed interface Timelines permits Timeline {
    RegistryKey<Timeline> DAY = RegistryKey.of("day");

    RegistryKey<Timeline> EARLY_GAME = RegistryKey.of("early_game");

    RegistryKey<Timeline> MOON = RegistryKey.of("moon");

    RegistryKey<Timeline> VILLAGER_SCHEDULE = RegistryKey.of("villager_schedule");
}
