version: 2

updates:
    # For the master branch we want to not include major updates
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    groups:
      non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  # For the next branch, we include major updates
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
  # GH actions are often non breaking, just keep them up to date.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    groups:
      all-actions:
        patterns:
          - "*"