import org.gradle.kotlin.dsl.support.serviceOf

plugins {
    id("minestom.java-library")
    id("minestom.publishing")

    alias(libs.plugins.nmcp.aggregation)
    alias(libs.plugins.graalvm.native)
}

// The root project is the aggregate `minestom` artifact: the classes of :lib and
// :framework merged into a single modular jar carrying module-info.java, so that
// module-path consumers (`requires net.minestom.server`) are unaffected by the split.
// The two subproject jars are embedded, not declared as pom dependencies.
val aggregateContents: Configuration by configurations.creating {
    isCanBeConsumed = false
    isTransitive = false
}

dependencies {
    aggregateContents(project(":lib"))
    aggregateContents(project(":framework"))

    // External dependencies, re-declared for the aggregate pom (same as pre-split).
    api(libs.bundles.adventure)
    implementation(libs.slf4j)
    implementation(libs.minestomData)
    implementation(libs.fastutil)
    implementation(libs.bundles.flare)
    api(libs.gson)
    implementation(libs.jcTools)

    testImplementation(project(":testing"))
}

// src/main/java holds only module-info.java; the exported packages come from the
// patched-in subproject classes.
tasks.compileJava {
    val patchArg = aggregateContents.elements.map { jars ->
        "net.minestom.server=" + jars.joinToString(File.pathSeparator) { it.asFile.absolutePath }
    }
    inputs.files(aggregateContents)
    options.compilerArgumentProviders.add(CommandLineArgumentProvider {
        listOf("--patch-module", patchArg.get())
    })
}

tasks.jar {
    val archives = project.serviceOf<org.gradle.api.file.ArchiveOperations>()
    from(aggregateContents.elements.map { jars -> jars.map { archives.zipTree(it) } }) {
        exclude("META-INF/MANIFEST.MF")
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Project consumers (testing/demo/benchmarks) must resolve the merged jar, not the
// nearly-empty classes dir (module-info only) that the classes secondary variant exposes.
configurations.apiElements { outgoing.variants.clear() }
configurations.runtimeElements { outgoing.variants.clear() }

tasks.named<Jar>("sourcesJar") {
    from(files("lib/src/main/java", "lib/src/autogenerated/java", "lib/src/main/resources",
            "framework/src/main/java", "framework/src/main/resources"))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Javadoc cannot resolve split packages spread over several source roots, so the
// aggregate documentation runs over a single merged tree. Framework package-infos are
// dropped: the split packages duplicate them (@NotNullByDefault must annotate both
// compilations) and javadoc rejects the duplicates.
val mergeJavadocSources by tasks.registering(Sync::class) {
    into(layout.buildDirectory.dir("javadoc-sources"))
    from("lib/src/main/java", "lib/src/autogenerated/java")
    from("framework/src/main/java") {
        exclude("**/package-info.java")
    }
}

tasks.javadoc {
    dependsOn(mergeJavadocSources)
    setSource(layout.buildDirectory.dir("javadoc-sources"))
    classpath += aggregateContents
    modularity.inferModulePath = false
}

// The test suite exercises the aggregate on the classpath (split packages are legal there).
tasks.compileTestJava {
    modularity.inferModulePath = false
}
tasks.test {
    modularity.inferModulePath = false
}

tasks.register<Task>("determineMinecraftVersion") {
    outputs.upToDateWhen { false } // Never cache

    doLast {
        val minestomDataVersion = libs.minestomData.get().version
        if (minestomDataVersion == null || "-" !in minestomDataVersion)
            throw IllegalStateException("Unable to determine Minecraft version from minestomData dependency")
        println(minestomDataVersion.split("-")[0])
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-Xlint:-requires-transitive-automatic") // Adventure dependencies are automatic until 5.0.0, see https://github.com/KyoriPowered/adventure/issues/1287
}

graalvmNative {
    agent {
        defaultMode = "standard"

        modes {
            standard {
                val file = layout.projectDirectory.file("src/test/resources/agent-filter.json").asFile.absolutePath
                callerFilterFiles.from(file)
                accessFilterFiles.from(file)
            }
        }

        metadataCopy {
            inputTaskNames.add("test")
            outputDirectories.add("src/main/resources/META-INF/native-image/net.minestom/minestom")
            mergeWithExisting.set(true)
        }
    }
    binaries {
        named("test") {
            buildArgs.add("-Ob")

            systemProperties.put("minestom.viewable-packet", "false")
            systemProperties.put("minestom.inside-test", "true")
            systemProperties.put("minestom.acquirable-strict", "true")

            runtimeArgs.add("-Dminestom.viewable-packet=false")
            runtimeArgs.add("-Dminestom.inside-test=true")
            runtimeArgs.add("-Dminestom.acquirable-strict=true")
        }
    }
}

// Publishing configuration below

nmcpAggregation {
    centralPortal {
        username = System.getenv("SONATYPE_USERNAME")
        password = System.getenv("SONATYPE_PASSWORD")
        publishingType = "AUTOMATIC"
    }
}

dependencies {
    nmcpAggregation(rootProject)
    nmcpAggregation(project(":lib"))
    nmcpAggregation(project(":framework"))
    nmcpAggregation(project(":testing"))
}
