package net.minestom.server.potion;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface PotionTypes {
    PotionType EMPTY = PotionTypeImpl.get("minecraft:empty");

    PotionType WATER = PotionTypeImpl.get("minecraft:water");

    PotionType MUNDANE = PotionTypeImpl.get("minecraft:mundane");

    PotionType THICK = PotionTypeImpl.get("minecraft:thick");

    PotionType AWKWARD = PotionTypeImpl.get("minecraft:awkward");

    PotionType NIGHT_VISION = PotionTypeImpl.get("minecraft:night_vision");

    PotionType LONG_NIGHT_VISION = PotionTypeImpl.get("minecraft:long_night_vision");

    PotionType INVISIBILITY = PotionTypeImpl.get("minecraft:invisibility");

    PotionType LONG_INVISIBILITY = PotionTypeImpl.get("minecraft:long_invisibility");

    PotionType LEAPING = PotionTypeImpl.get("minecraft:leaping");

    PotionType LONG_LEAPING = PotionTypeImpl.get("minecraft:long_leaping");

    PotionType STRONG_LEAPING = PotionTypeImpl.get("minecraft:strong_leaping");

    PotionType FIRE_RESISTANCE = PotionTypeImpl.get("minecraft:fire_resistance");

    PotionType LONG_FIRE_RESISTANCE = PotionTypeImpl.get("minecraft:long_fire_resistance");

    PotionType SWIFTNESS = PotionTypeImpl.get("minecraft:swiftness");

    PotionType LONG_SWIFTNESS = PotionTypeImpl.get("minecraft:long_swiftness");

    PotionType STRONG_SWIFTNESS = PotionTypeImpl.get("minecraft:strong_swiftness");

    PotionType SLOWNESS = PotionTypeImpl.get("minecraft:slowness");

    PotionType LONG_SLOWNESS = PotionTypeImpl.get("minecraft:long_slowness");

    PotionType STRONG_SLOWNESS = PotionTypeImpl.get("minecraft:strong_slowness");

    PotionType TURTLE_MASTER = PotionTypeImpl.get("minecraft:turtle_master");

    PotionType LONG_TURTLE_MASTER = PotionTypeImpl.get("minecraft:long_turtle_master");

    PotionType STRONG_TURTLE_MASTER = PotionTypeImpl.get("minecraft:strong_turtle_master");

    PotionType WATER_BREATHING = PotionTypeImpl.get("minecraft:water_breathing");

    PotionType LONG_WATER_BREATHING = PotionTypeImpl.get("minecraft:long_water_breathing");

    PotionType HEALING = PotionTypeImpl.get("minecraft:healing");

    PotionType STRONG_HEALING = PotionTypeImpl.get("minecraft:strong_healing");

    PotionType HARMING = PotionTypeImpl.get("minecraft:harming");

    PotionType STRONG_HARMING = PotionTypeImpl.get("minecraft:strong_harming");

    PotionType POISON = PotionTypeImpl.get("minecraft:poison");

    PotionType LONG_POISON = PotionTypeImpl.get("minecraft:long_poison");

    PotionType STRONG_POISON = PotionTypeImpl.get("minecraft:strong_poison");

    PotionType REGENERATION = PotionTypeImpl.get("minecraft:regeneration");

    PotionType LONG_REGENERATION = PotionTypeImpl.get("minecraft:long_regeneration");

    PotionType STRONG_REGENERATION = PotionTypeImpl.get("minecraft:strong_regeneration");

    PotionType STRENGTH = PotionTypeImpl.get("minecraft:strength");

    PotionType LONG_STRENGTH = PotionTypeImpl.get("minecraft:long_strength");

    PotionType STRONG_STRENGTH = PotionTypeImpl.get("minecraft:strong_strength");

    PotionType WEAKNESS = PotionTypeImpl.get("minecraft:weakness");

    PotionType LONG_WEAKNESS = PotionTypeImpl.get("minecraft:long_weakness");

    PotionType LUCK = PotionTypeImpl.get("minecraft:luck");

    PotionType SLOW_FALLING = PotionTypeImpl.get("minecraft:slow_falling");

    PotionType LONG_SLOW_FALLING = PotionTypeImpl.get("minecraft:long_slow_falling");
}
