plugins {
    id("minestom.java-binary")
}

dependencies {
    // Provides the input JSON to generate from
    implementation(libs.minestomData)

    // Common
    implementation(libs.jetbrainsAnnotations)
    implementation(libs.jSpecify)
    implementation(libs.slf4j)
    implementation(libs.bundles.adventure)
    runtimeOnly(libs.bundles.logback)

    // Parsing and generation
    implementation(libs.gson)
    implementation(libs.javaPoet)
}

application {
    mainClass.set("net.minestom.codegen.Generators")
}

tasks.getByName<JavaExec>("run") {
    args = listOf(rootProject.projectDir.resolve("src/autogenerated/java").absolutePath)
}
