package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class AcaciaTrapdoor {
  public static void initStates() {
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4367, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4368, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4369, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4370, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4371, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4372, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4373, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4374, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4375, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4376, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4377, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4378, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4379, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4380, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4381, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4382, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4383, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4384, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4385, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4386, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4387, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4388, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4389, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4390, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4391, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4392, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4393, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4394, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4395, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4396, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4397, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4398, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4399, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4400, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4401, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4402, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4403, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4404, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4405, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4406, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4407, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4408, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4409, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4410, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4411, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4412, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4413, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4414, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4415, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4416, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4417, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4418, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4419, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4420, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4421, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4422, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4423, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4424, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4425, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4426, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4427, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4428, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4429, Block.ACACIA_TRAPDOOR));
    Block.ACACIA_TRAPDOOR.addBlockState(new BlockState((short) 4430, Block.ACACIA_TRAPDOOR));
  }
}
