package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class AcaciaStairs {
	public static void initStates() {
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7379, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7380, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7381, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7382, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7383, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7384, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7385, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7386, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7387, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7388, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7389, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7390, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7391, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7392, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7393, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7394, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7395, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7396, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7397, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7398, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7399, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7400, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7401, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7402, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7403, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7404, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7405, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7406, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7407, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7408, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7409, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7410, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7411, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7412, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7413, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7414, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7415, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7416, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7417, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7418, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7419, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7420, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7421, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7422, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7423, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7424, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7425, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7426, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7427, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7428, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7429, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7430, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7431, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7432, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7433, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7434, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7435, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7436, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7437, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7438, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7439, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7440, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7441, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7442, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7443, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7444, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7445, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7446, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7447, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7448, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7449, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7450, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7451, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7452, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7453, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7454, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7455, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7456, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7457, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ACACIA_STAIRS.addBlockAlternative(new BlockAlternative((short) 7458, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
