package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class AcaciaLeaves {
  public static final BlockState ACACIA_LEAVES_0 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_0"), (short) 201, Block.ACACIA_LEAVES, "distance=1","persistent=true");

  public static final BlockState ACACIA_LEAVES_1 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_1"), (short) 202, Block.ACACIA_LEAVES, "distance=1","persistent=false");

  public static final BlockState ACACIA_LEAVES_2 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_2"), (short) 203, Block.ACACIA_LEAVES, "distance=2","persistent=true");

  public static final BlockState ACACIA_LEAVES_3 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_3"), (short) 204, Block.ACACIA_LEAVES, "distance=2","persistent=false");

  public static final BlockState ACACIA_LEAVES_4 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_4"), (short) 205, Block.ACACIA_LEAVES, "distance=3","persistent=true");

  public static final BlockState ACACIA_LEAVES_5 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_5"), (short) 206, Block.ACACIA_LEAVES, "distance=3","persistent=false");

  public static final BlockState ACACIA_LEAVES_6 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_6"), (short) 207, Block.ACACIA_LEAVES, "distance=4","persistent=true");

  public static final BlockState ACACIA_LEAVES_7 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_7"), (short) 208, Block.ACACIA_LEAVES, "distance=4","persistent=false");

  public static final BlockState ACACIA_LEAVES_8 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_8"), (short) 209, Block.ACACIA_LEAVES, "distance=5","persistent=true");

  public static final BlockState ACACIA_LEAVES_9 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_9"), (short) 210, Block.ACACIA_LEAVES, "distance=5","persistent=false");

  public static final BlockState ACACIA_LEAVES_10 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_10"), (short) 211, Block.ACACIA_LEAVES, "distance=6","persistent=true");

  public static final BlockState ACACIA_LEAVES_11 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_11"), (short) 212, Block.ACACIA_LEAVES, "distance=6","persistent=false");

  public static final BlockState ACACIA_LEAVES_12 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_12"), (short) 213, Block.ACACIA_LEAVES, "distance=7","persistent=true");

  public static final BlockState ACACIA_LEAVES_13 = new BlockState(NamespaceID.from("minecraft:acacia_leaves_13"), (short) 214, Block.ACACIA_LEAVES, "distance=7","persistent=false");

  static {
    Registries.registerBlockState(ACACIA_LEAVES_0);
    Registries.registerBlockState(ACACIA_LEAVES_1);
    Registries.registerBlockState(ACACIA_LEAVES_2);
    Registries.registerBlockState(ACACIA_LEAVES_3);
    Registries.registerBlockState(ACACIA_LEAVES_4);
    Registries.registerBlockState(ACACIA_LEAVES_5);
    Registries.registerBlockState(ACACIA_LEAVES_6);
    Registries.registerBlockState(ACACIA_LEAVES_7);
    Registries.registerBlockState(ACACIA_LEAVES_8);
    Registries.registerBlockState(ACACIA_LEAVES_9);
    Registries.registerBlockState(ACACIA_LEAVES_10);
    Registries.registerBlockState(ACACIA_LEAVES_11);
    Registries.registerBlockState(ACACIA_LEAVES_12);
    Registries.registerBlockState(ACACIA_LEAVES_13);
  }

  public static void initStates() {
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_0);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_1);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_2);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_3);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_4);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_5);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_6);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_7);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_8);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_9);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_10);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_11);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_12);
    Block.ACACIA_LEAVES.addBlockState(ACACIA_LEAVES_13);
  }
}
