package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Allium {
  public static void initStates() {
    Block.ALLIUM.addBlockState(new BlockState((short) 1415, Block.ALLIUM));
  }
}
