package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class AndesiteStairs {
	public static void initStates() {
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10473, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10474, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10475, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10476, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10477, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10478, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10479, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10480, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10481, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10482, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10483, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10484, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10485, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10486, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10487, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10488, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10489, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10490, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10491, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10492, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10493, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10494, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10495, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10496, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10497, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10498, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10499, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10500, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10501, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10502, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10503, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10504, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10505, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10506, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10507, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10508, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10509, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10510, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10511, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10512, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10513, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10514, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10515, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10516, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10517, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10518, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10519, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10520, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10521, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10522, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10523, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10524, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10525, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10526, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10527, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10528, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10529, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10530, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10531, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10532, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10533, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10534, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10535, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10536, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10537, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10538, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10539, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10540, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10541, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10542, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10543, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10544, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10545, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10546, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10547, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10548, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10549, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10550, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10551, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10552, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
