package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BeeNest {
  public static void initStates() {
    Block.BEE_NEST.addBlockState(new BlockState((short) 15784, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15785, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15786, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15787, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15788, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15789, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15790, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15791, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15792, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15793, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15794, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15795, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15796, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15797, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15798, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15799, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15800, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15801, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15802, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15803, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15804, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15805, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15806, Block.BEE_NEST));
    Block.BEE_NEST.addBlockState(new BlockState((short) 15807, Block.BEE_NEST));
  }
}
