package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class BirchWood {
    public static void initStates() {
        Block.BIRCH_WOOD.addBlockAlternative(new BlockAlternative((short) 115, "axis=x"));
        Block.BIRCH_WOOD.addBlockAlternative(new BlockAlternative((short) 116, "axis=y"));
        Block.BIRCH_WOOD.addBlockAlternative(new BlockAlternative((short) 117, "axis=z"));
    }
}
