package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class BirchStairs {
	public static void initStates() {
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5488, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5489, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5490, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5491, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5492, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5493, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5494, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5495, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5496, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5497, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5498, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5499, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5500, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5501, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5502, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5503, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5504, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5505, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5506, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5507, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5508, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5509, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5510, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5511, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5512, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5513, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5514, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5515, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5516, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5517, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5518, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5519, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5520, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5521, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5522, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5523, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5524, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5525, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5526, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5527, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5528, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5529, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5530, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5531, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5532, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5533, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5534, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5535, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5536, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5537, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5538, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5539, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5540, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5541, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5542, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5543, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5544, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5545, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5546, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5547, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5548, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5549, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5550, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5551, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5552, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5553, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5554, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5555, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5556, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5557, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5558, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5559, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5560, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5561, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5562, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5563, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5564, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5565, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5566, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BIRCH_STAIRS.addBlockAlternative(new BlockAlternative((short) 5567, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
