package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class BirchTrapdoor {
    public static final BlockState BIRCH_TRAPDOOR_0 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_0"), (short) 4239, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_1 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_1"), (short) 4240, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_2 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_2"), (short) 4241, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_3 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_3"), (short) 4242, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_4 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_4"), (short) 4243, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_5 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_5"), (short) 4244, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_6 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_6"), (short) 4245, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_7 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_7"), (short) 4246, Block.BIRCH_TRAPDOOR, "facing=north","half=top","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_8 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_8"), (short) 4247, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_9 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_9"), (short) 4248, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_10 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_10"), (short) 4249, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_11 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_11"), (short) 4250, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_12 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_12"), (short) 4251, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_13 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_13"), (short) 4252, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_14 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_14"), (short) 4253, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_15 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_15"), (short) 4254, Block.BIRCH_TRAPDOOR, "facing=north","half=bottom","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_16 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_16"), (short) 4255, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_17 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_17"), (short) 4256, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_18 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_18"), (short) 4257, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_19 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_19"), (short) 4258, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_20 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_20"), (short) 4259, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_21 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_21"), (short) 4260, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_22 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_22"), (short) 4261, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_23 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_23"), (short) 4262, Block.BIRCH_TRAPDOOR, "facing=south","half=top","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_24 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_24"), (short) 4263, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_25 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_25"), (short) 4264, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_26 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_26"), (short) 4265, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_27 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_27"), (short) 4266, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_28 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_28"), (short) 4267, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_29 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_29"), (short) 4268, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_30 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_30"), (short) 4269, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_31 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_31"), (short) 4270, Block.BIRCH_TRAPDOOR, "facing=south","half=bottom","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_32 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_32"), (short) 4271, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_33 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_33"), (short) 4272, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_34 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_34"), (short) 4273, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_35 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_35"), (short) 4274, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_36 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_36"), (short) 4275, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_37 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_37"), (short) 4276, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_38 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_38"), (short) 4277, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_39 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_39"), (short) 4278, Block.BIRCH_TRAPDOOR, "facing=west","half=top","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_40 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_40"), (short) 4279, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_41 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_41"), (short) 4280, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_42 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_42"), (short) 4281, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_43 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_43"), (short) 4282, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_44 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_44"), (short) 4283, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_45 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_45"), (short) 4284, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_46 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_46"), (short) 4285, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_47 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_47"), (short) 4286, Block.BIRCH_TRAPDOOR, "facing=west","half=bottom","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_48 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_48"), (short) 4287, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_49 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_49"), (short) 4288, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_50 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_50"), (short) 4289, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_51 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_51"), (short) 4290, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_52 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_52"), (short) 4291, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_53 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_53"), (short) 4292, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_54 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_54"), (short) 4293, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_55 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_55"), (short) 4294, Block.BIRCH_TRAPDOOR, "facing=east","half=top","open=false","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_56 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_56"), (short) 4295, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=true","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_57 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_57"), (short) 4296, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=true","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_58 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_58"), (short) 4297, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=true","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_59 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_59"), (short) 4298, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=true","powered=false","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_60 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_60"), (short) 4299, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=false","powered=true","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_61 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_61"), (short) 4300, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=false","powered=true","waterlogged=false");

    public static final BlockState BIRCH_TRAPDOOR_62 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_62"), (short) 4301, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=false","powered=false","waterlogged=true");

    public static final BlockState BIRCH_TRAPDOOR_63 = new BlockState(NamespaceID.from("minecraft:birch_trapdoor_63"), (short) 4302, Block.BIRCH_TRAPDOOR, "facing=east","half=bottom","open=false","powered=false","waterlogged=false");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_0);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_1);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_2);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_3);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_4);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_5);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_6);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_7);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_8);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_9);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_10);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_11);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_12);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_13);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_14);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_15);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_16);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_17);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_18);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_19);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_20);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_21);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_22);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_23);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_24);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_25);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_26);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_27);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_28);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_29);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_30);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_31);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_32);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_33);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_34);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_35);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_36);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_37);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_38);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_39);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_40);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_41);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_42);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_43);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_44);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_45);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_46);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_47);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_48);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_49);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_50);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_51);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_52);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_53);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_54);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_55);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_56);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_57);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_58);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_59);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_60);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_61);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_62);
        Registry.BLOCK_STATE_REGISTRY.register(BIRCH_TRAPDOOR_63);
    }

    public static void initStates() {
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_0);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_1);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_2);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_3);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_4);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_5);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_6);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_7);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_8);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_9);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_10);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_11);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_12);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_13);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_14);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_15);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_16);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_17);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_18);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_19);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_20);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_21);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_22);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_23);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_24);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_25);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_26);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_27);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_28);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_29);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_30);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_31);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_32);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_33);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_34);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_35);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_36);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_37);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_38);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_39);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_40);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_41);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_42);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_43);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_44);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_45);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_46);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_47);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_48);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_49);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_50);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_51);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_52);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_53);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_54);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_55);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_56);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_57);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_58);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_59);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_60);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_61);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_62);
        Block.BIRCH_TRAPDOOR.addBlockState(BIRCH_TRAPDOOR_63);
    }
}
