package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class BlackstoneStairs {
	public static void initStates() {
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15848, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15849, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15850, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15851, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15852, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15853, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15854, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15855, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15856, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15857, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15858, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15859, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15860, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15861, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15862, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15863, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15864, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15865, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15866, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15867, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15868, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15869, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15870, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15871, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15872, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15873, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15874, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15875, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15876, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15877, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15878, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15879, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15880, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15881, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15882, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15883, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15884, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15885, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15886, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15887, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15888, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15889, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15890, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15891, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15892, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15893, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15894, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15895, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15896, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15897, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15898, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15899, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15900, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15901, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15902, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15903, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15904, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15905, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15906, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15907, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15908, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15909, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15910, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15911, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15912, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15913, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15914, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15915, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15916, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15917, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15918, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15919, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15920, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15921, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15922, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15923, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15924, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15925, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15926, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 15927, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
