package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BlackShulkerBox {
  public static void initStates() {
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9372, Block.BLACK_SHULKER_BOX));
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9373, Block.BLACK_SHULKER_BOX));
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9374, Block.BLACK_SHULKER_BOX));
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9375, Block.BLACK_SHULKER_BOX));
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9376, Block.BLACK_SHULKER_BOX));
    Block.BLACK_SHULKER_BOX.addBlockState(new BlockState((short) 9377, Block.BLACK_SHULKER_BOX));
  }
}
