package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BlueBanner {
  public static final BlockState BLUE_BANNER_0 = new BlockState(NamespaceID.from("minecraft:blue_banner:0"), (short) 8077, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_1 = new BlockState(NamespaceID.from("minecraft:blue_banner:1"), (short) 8078, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_2 = new BlockState(NamespaceID.from("minecraft:blue_banner:2"), (short) 8079, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_3 = new BlockState(NamespaceID.from("minecraft:blue_banner:3"), (short) 8080, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_4 = new BlockState(NamespaceID.from("minecraft:blue_banner:4"), (short) 8081, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_5 = new BlockState(NamespaceID.from("minecraft:blue_banner:5"), (short) 8082, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_6 = new BlockState(NamespaceID.from("minecraft:blue_banner:6"), (short) 8083, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_7 = new BlockState(NamespaceID.from("minecraft:blue_banner:7"), (short) 8084, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_8 = new BlockState(NamespaceID.from("minecraft:blue_banner:8"), (short) 8085, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_9 = new BlockState(NamespaceID.from("minecraft:blue_banner:9"), (short) 8086, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_10 = new BlockState(NamespaceID.from("minecraft:blue_banner:10"), (short) 8087, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_11 = new BlockState(NamespaceID.from("minecraft:blue_banner:11"), (short) 8088, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_12 = new BlockState(NamespaceID.from("minecraft:blue_banner:12"), (short) 8089, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_13 = new BlockState(NamespaceID.from("minecraft:blue_banner:13"), (short) 8090, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_14 = new BlockState(NamespaceID.from("minecraft:blue_banner:14"), (short) 8091, Block.BLUE_BANNER);

  public static final BlockState BLUE_BANNER_15 = new BlockState(NamespaceID.from("minecraft:blue_banner:15"), (short) 8092, Block.BLUE_BANNER);

  public static void initStates() {
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_0);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_1);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_2);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_3);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_4);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_5);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_6);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_7);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_8);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_9);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_10);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_11);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_12);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_13);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_14);
    Block.BLUE_BANNER.addBlockState(BLUE_BANNER_15);
  }
}
