package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BlueTerracotta {
  public static void initStates() {
    Block.BLUE_TERRACOTTA.addBlockState(new BlockState((short) 6862, Block.BLUE_TERRACOTTA));
  }
}
