package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class BrainCoral {
    public static final BlockState BRAIN_CORAL_0 = new BlockState(NamespaceID.from("minecraft:brain_coral_0"), (short) 9536, Block.BRAIN_CORAL, new RawBlockStateData(0.0, 0, false, "DESTROY", false, false, false, false, false, false, 12, "[]"), "waterlogged=true");

    public static final BlockState BRAIN_CORAL_1 = new BlockState(NamespaceID.from("minecraft:brain_coral_1"), (short) 9537, Block.BRAIN_CORAL, new RawBlockStateData(0.0, 0, false, "DESTROY", false, false, false, false, false, false, 12, "[]"), "waterlogged=false");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(BRAIN_CORAL_0);
        Registry.BLOCK_STATE_REGISTRY.register(BRAIN_CORAL_1);
    }

    public static void initStates() {
        Block.BRAIN_CORAL.addBlockState(BRAIN_CORAL_0);
        Block.BRAIN_CORAL.addBlockState(BRAIN_CORAL_1);
    }
}
