package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class BrickStairs {
	public static void initStates() {
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4856, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4857, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4858, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4859, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4860, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4861, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4862, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4863, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4864, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4865, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4866, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4867, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4868, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4869, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4870, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4871, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4872, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4873, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4874, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4875, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4876, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4877, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4878, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4879, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4880, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4881, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4882, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4883, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4884, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4885, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4886, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4887, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4888, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4889, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4890, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4891, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4892, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4893, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4894, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4895, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4896, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4897, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4898, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4899, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4900, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4901, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4902, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4903, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4904, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4905, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4906, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4907, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4908, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4909, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4910, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4911, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4912, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4913, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4914, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4915, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4916, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4917, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4918, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4919, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4920, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4921, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4922, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4923, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4924, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4925, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4926, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4927, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4928, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4929, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4930, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4931, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4932, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4933, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4934, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4935, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
