package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BrownBed {
  public static void initStates() {
    Block.BROWN_BED.addBlockState(new BlockState((short) 1241, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1242, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1243, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1244, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1245, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1246, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1247, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1248, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1249, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1250, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1251, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1252, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1253, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1254, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1255, Block.BROWN_BED));
    Block.BROWN_BED.addBlockState(new BlockState((short) 1256, Block.BROWN_BED));
  }
}
