package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class BubbleCoralWallFan {
  public static void initStates() {
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9620, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9621, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9622, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9623, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9624, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9625, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9626, Block.BUBBLE_CORAL_WALL_FAN));
    Block.BUBBLE_CORAL_WALL_FAN.addBlockState(new BlockState((short) 9627, Block.BUBBLE_CORAL_WALL_FAN));
  }
}
