package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class CartographyTable {
    public static final BlockState CARTOGRAPHY_TABLE_0 = new BlockState(NamespaceID.from("minecraft:cartography_table_0"), (short) 14823, Block.CARTOGRAPHY_TABLE, new RawBlockStateData(2.5, 0, true, "NORMAL", true, true, false, false, true, true, 13, "[AABB[0.0, 0.0, 0.0] -> [1.0, 1.0, 1.0]]"));

    static {
        Registry.BLOCK_STATE_REGISTRY.register(CARTOGRAPHY_TABLE_0);
    }

    public static void initStates() {
        Block.CARTOGRAPHY_TABLE.addBlockState(CARTOGRAPHY_TABLE_0);
    }
}
