package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class Cobblestone {
    public static void initStates() {
        Block.COBBLESTONE.addBlockAlternative(new BlockAlternative((short) 14));
    }
}
