package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class CobblestoneSlab {
    public static void initStates() {
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8370, "type=top","waterlogged=true"));
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8371, "type=top","waterlogged=false"));
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8372, "type=bottom","waterlogged=true"));
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8373, "type=bottom","waterlogged=false"));
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8374, "type=double","waterlogged=true"));
        Block.COBBLESTONE_SLAB.addBlockAlternative(new BlockAlternative((short) 8375, "type=double","waterlogged=false"));
    }
}
