package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class CobblestoneStairs {
	public static void initStates() {
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3655, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3656, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3657, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3658, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3659, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3660, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3661, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3662, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3663, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3664, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3665, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3666, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3667, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3668, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3669, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3670, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3671, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3672, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3673, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3674, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3675, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3676, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3677, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3678, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3679, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3680, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3681, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3682, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3683, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3684, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3685, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3686, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3687, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3688, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3689, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3690, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3691, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3692, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3693, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3694, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3695, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3696, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3697, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3698, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3699, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3700, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3701, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3702, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3703, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3704, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3705, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3706, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3707, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3708, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3709, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3710, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3711, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3712, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3713, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3714, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3715, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3716, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3717, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3718, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3719, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3720, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3721, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3722, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3723, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3724, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3725, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3726, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3727, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3728, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3729, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3730, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3731, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3732, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3733, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 3734, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
