package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class CreeperHead {
  public static final BlockState CREEPER_HEAD_0 = new BlockState(NamespaceID.from("minecraft:creeper_head_0"), (short) 6574, Block.CREEPER_HEAD, "rotation=0");

  public static final BlockState CREEPER_HEAD_1 = new BlockState(NamespaceID.from("minecraft:creeper_head_1"), (short) 6575, Block.CREEPER_HEAD, "rotation=1");

  public static final BlockState CREEPER_HEAD_2 = new BlockState(NamespaceID.from("minecraft:creeper_head_2"), (short) 6576, Block.CREEPER_HEAD, "rotation=2");

  public static final BlockState CREEPER_HEAD_3 = new BlockState(NamespaceID.from("minecraft:creeper_head_3"), (short) 6577, Block.CREEPER_HEAD, "rotation=3");

  public static final BlockState CREEPER_HEAD_4 = new BlockState(NamespaceID.from("minecraft:creeper_head_4"), (short) 6578, Block.CREEPER_HEAD, "rotation=4");

  public static final BlockState CREEPER_HEAD_5 = new BlockState(NamespaceID.from("minecraft:creeper_head_5"), (short) 6579, Block.CREEPER_HEAD, "rotation=5");

  public static final BlockState CREEPER_HEAD_6 = new BlockState(NamespaceID.from("minecraft:creeper_head_6"), (short) 6580, Block.CREEPER_HEAD, "rotation=6");

  public static final BlockState CREEPER_HEAD_7 = new BlockState(NamespaceID.from("minecraft:creeper_head_7"), (short) 6581, Block.CREEPER_HEAD, "rotation=7");

  public static final BlockState CREEPER_HEAD_8 = new BlockState(NamespaceID.from("minecraft:creeper_head_8"), (short) 6582, Block.CREEPER_HEAD, "rotation=8");

  public static final BlockState CREEPER_HEAD_9 = new BlockState(NamespaceID.from("minecraft:creeper_head_9"), (short) 6583, Block.CREEPER_HEAD, "rotation=9");

  public static final BlockState CREEPER_HEAD_10 = new BlockState(NamespaceID.from("minecraft:creeper_head_10"), (short) 6584, Block.CREEPER_HEAD, "rotation=10");

  public static final BlockState CREEPER_HEAD_11 = new BlockState(NamespaceID.from("minecraft:creeper_head_11"), (short) 6585, Block.CREEPER_HEAD, "rotation=11");

  public static final BlockState CREEPER_HEAD_12 = new BlockState(NamespaceID.from("minecraft:creeper_head_12"), (short) 6586, Block.CREEPER_HEAD, "rotation=12");

  public static final BlockState CREEPER_HEAD_13 = new BlockState(NamespaceID.from("minecraft:creeper_head_13"), (short) 6587, Block.CREEPER_HEAD, "rotation=13");

  public static final BlockState CREEPER_HEAD_14 = new BlockState(NamespaceID.from("minecraft:creeper_head_14"), (short) 6588, Block.CREEPER_HEAD, "rotation=14");

  public static final BlockState CREEPER_HEAD_15 = new BlockState(NamespaceID.from("minecraft:creeper_head_15"), (short) 6589, Block.CREEPER_HEAD, "rotation=15");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_0);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_1);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_2);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_3);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_4);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_5);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_6);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_7);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_8);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_9);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_10);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_11);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_12);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_13);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_14);
    Registry.BLOCK_STATE_REGISTRY.register(CREEPER_HEAD_15);
  }

  public static void initStates() {
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_0);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_1);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_2);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_3);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_4);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_5);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_6);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_7);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_8);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_9);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_10);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_11);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_12);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_13);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_14);
    Block.CREEPER_HEAD.addBlockState(CREEPER_HEAD_15);
  }
}
