package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class CrimsonStem {
  public static final BlockState CRIMSON_STEM_0 = new BlockState(NamespaceID.from("minecraft:crimson_stem_0"), (short) 14983, Block.CRIMSON_STEM, "axis=x");

  public static final BlockState CRIMSON_STEM_1 = new BlockState(NamespaceID.from("minecraft:crimson_stem_1"), (short) 14984, Block.CRIMSON_STEM, "axis=y");

  public static final BlockState CRIMSON_STEM_2 = new BlockState(NamespaceID.from("minecraft:crimson_stem_2"), (short) 14985, Block.CRIMSON_STEM, "axis=z");

  static {
    Registries.registerBlockState(CRIMSON_STEM_0);
    Registries.registerBlockState(CRIMSON_STEM_1);
    Registries.registerBlockState(CRIMSON_STEM_2);
  }

  public static void initStates() {
    Block.CRIMSON_STEM.addBlockState(CRIMSON_STEM_0);
    Block.CRIMSON_STEM.addBlockState(CRIMSON_STEM_1);
    Block.CRIMSON_STEM.addBlockState(CRIMSON_STEM_2);
  }
}
