package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class CrimsonTrapdoor {
  public static final BlockState CRIMSON_TRAPDOOR_0 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:0"), (short) 15135, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_1 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:1"), (short) 15136, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_2 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:2"), (short) 15137, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_3 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:3"), (short) 15138, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_4 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:4"), (short) 15139, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_5 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:5"), (short) 15140, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_6 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:6"), (short) 15141, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_7 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:7"), (short) 15142, Block.CRIMSON_TRAPDOOR, "facing=north","half=top","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_8 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:8"), (short) 15143, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_9 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:9"), (short) 15144, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_10 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:10"), (short) 15145, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_11 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:11"), (short) 15146, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_12 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:12"), (short) 15147, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_13 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:13"), (short) 15148, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_14 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:14"), (short) 15149, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_15 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:15"), (short) 15150, Block.CRIMSON_TRAPDOOR, "facing=north","half=bottom","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_16 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:16"), (short) 15151, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_17 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:17"), (short) 15152, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_18 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:18"), (short) 15153, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_19 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:19"), (short) 15154, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_20 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:20"), (short) 15155, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_21 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:21"), (short) 15156, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_22 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:22"), (short) 15157, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_23 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:23"), (short) 15158, Block.CRIMSON_TRAPDOOR, "facing=south","half=top","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_24 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:24"), (short) 15159, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_25 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:25"), (short) 15160, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_26 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:26"), (short) 15161, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_27 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:27"), (short) 15162, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_28 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:28"), (short) 15163, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_29 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:29"), (short) 15164, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_30 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:30"), (short) 15165, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_31 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:31"), (short) 15166, Block.CRIMSON_TRAPDOOR, "facing=south","half=bottom","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_32 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:32"), (short) 15167, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_33 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:33"), (short) 15168, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_34 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:34"), (short) 15169, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_35 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:35"), (short) 15170, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_36 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:36"), (short) 15171, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_37 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:37"), (short) 15172, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_38 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:38"), (short) 15173, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_39 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:39"), (short) 15174, Block.CRIMSON_TRAPDOOR, "facing=west","half=top","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_40 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:40"), (short) 15175, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_41 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:41"), (short) 15176, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_42 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:42"), (short) 15177, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_43 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:43"), (short) 15178, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_44 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:44"), (short) 15179, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_45 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:45"), (short) 15180, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_46 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:46"), (short) 15181, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_47 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:47"), (short) 15182, Block.CRIMSON_TRAPDOOR, "facing=west","half=bottom","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_48 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:48"), (short) 15183, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_49 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:49"), (short) 15184, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_50 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:50"), (short) 15185, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_51 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:51"), (short) 15186, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_52 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:52"), (short) 15187, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_53 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:53"), (short) 15188, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_54 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:54"), (short) 15189, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_55 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:55"), (short) 15190, Block.CRIMSON_TRAPDOOR, "facing=east","half=top","open=false","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_56 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:56"), (short) 15191, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=true","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_57 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:57"), (short) 15192, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=true","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_58 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:58"), (short) 15193, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=true","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_59 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:59"), (short) 15194, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=true","powered=false","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_60 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:60"), (short) 15195, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=false","powered=true","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_61 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:61"), (short) 15196, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=false","powered=true","waterlogged=false");

  public static final BlockState CRIMSON_TRAPDOOR_62 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:62"), (short) 15197, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=false","powered=false","waterlogged=true");

  public static final BlockState CRIMSON_TRAPDOOR_63 = new BlockState(NamespaceID.from("minecraft:crimson_trapdoor:63"), (short) 15198, Block.CRIMSON_TRAPDOOR, "facing=east","half=bottom","open=false","powered=false","waterlogged=false");

  public static void initStates() {
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_0);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_1);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_2);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_3);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_4);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_5);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_6);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_7);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_8);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_9);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_10);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_11);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_12);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_13);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_14);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_15);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_16);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_17);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_18);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_19);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_20);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_21);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_22);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_23);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_24);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_25);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_26);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_27);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_28);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_29);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_30);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_31);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_32);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_33);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_34);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_35);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_36);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_37);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_38);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_39);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_40);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_41);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_42);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_43);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_44);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_45);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_46);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_47);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_48);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_49);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_50);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_51);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_52);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_53);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_54);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_55);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_56);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_57);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_58);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_59);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_60);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_61);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_62);
    Block.CRIMSON_TRAPDOOR.addBlockState(CRIMSON_TRAPDOOR_63);
  }
}
