package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class CrimsonStairs {
	public static void initStates() {
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15327, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15328, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15329, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15330, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15331, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15332, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15333, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15334, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15335, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15336, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15337, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15338, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15339, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15340, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15341, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15342, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15343, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15344, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15345, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15346, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15347, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15348, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15349, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15350, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15351, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15352, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15353, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15354, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15355, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15356, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15357, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15358, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15359, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15360, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15361, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15362, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15363, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15364, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15365, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15366, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15367, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15368, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15369, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15370, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15371, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15372, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15373, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15374, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15375, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15376, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15377, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15378, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15379, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15380, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15381, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15382, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15383, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15384, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15385, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15386, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15387, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15388, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15389, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15390, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15391, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15392, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15393, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15394, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15395, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15396, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15397, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15398, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15399, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15400, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15401, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15402, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15403, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15404, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15405, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		CRIMSON_STAIRS.addBlockAlternative(new BlockAlternative((short) 15406, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
