package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class CrimsonSign {
  public static void initStates() {
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15663, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15664, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15665, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15666, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15667, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15668, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15669, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15670, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15671, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15672, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15673, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15674, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15675, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15676, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15677, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15678, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15679, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15680, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15681, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15682, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15683, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15684, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15685, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15686, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15687, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15688, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15689, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15690, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15691, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15692, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15693, Block.CRIMSON_SIGN));
    Block.CRIMSON_SIGN.addBlockState(new BlockState((short) 15694, Block.CRIMSON_SIGN));
  }
}
