package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class CyanStainedGlass {
    public static void initStates() {
        Block.CYAN_STAINED_GLASS.addBlockAlternative(new BlockAlternative((short) 4104));
    }
}
