package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class CyanStainedGlass {
    public static final BlockState CYAN_STAINED_GLASS_0 = new BlockState(NamespaceID.from("minecraft:cyan_stained_glass_0"), (short) 4104, Block.CYAN_STAINED_GLASS, new RawBlockStateData(0.3, 0, false, "NORMAL", true, false, false, false, true, false, 0, "[AABB[0.0, 0.0, 0.0] -> [1.0, 1.0, 1.0]]"));

    static {
        Registry.BLOCK_STATE_REGISTRY.register(CYAN_STAINED_GLASS_0);
    }

    public static void initStates() {
        Block.CYAN_STAINED_GLASS.addBlockState(CYAN_STAINED_GLASS_0);
    }
}
