package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class CyanCarpet {
    public static final BlockState CYAN_CARPET_0 = new BlockState(NamespaceID.from("minecraft:cyan_carpet_0"), (short) 7879, Block.CYAN_CARPET, new RawBlockStateData(0.1, 0, true, "NORMAL", false, true, false, false, false, false, 3, "[AABB[0.0, 0.0, 0.0] -> [1.0, 0.0625, 1.0]]"));

    static {
        Registry.BLOCK_STATE_REGISTRY.register(CYAN_CARPET_0);
    }

    public static void initStates() {
        Block.CYAN_CARPET.addBlockState(CYAN_CARPET_0);
    }
}
