package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class DarkOakPressurePlate {
  public static void initStates() {
    Block.DARK_OAK_PRESSURE_PLATE.addBlockState(new BlockState((short) 3883, Block.DARK_OAK_PRESSURE_PLATE));
    Block.DARK_OAK_PRESSURE_PLATE.addBlockState(new BlockState((short) 3884, Block.DARK_OAK_PRESSURE_PLATE));
  }
}
