package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class DarkOakSign {
  public static final BlockState DARK_OAK_SIGN_0 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:0"), (short) 3541, Block.DARK_OAK_SIGN, "rotation=0","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_1 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:1"), (short) 3542, Block.DARK_OAK_SIGN, "rotation=0","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_2 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:2"), (short) 3543, Block.DARK_OAK_SIGN, "rotation=1","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_3 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:3"), (short) 3544, Block.DARK_OAK_SIGN, "rotation=1","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_4 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:4"), (short) 3545, Block.DARK_OAK_SIGN, "rotation=2","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_5 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:5"), (short) 3546, Block.DARK_OAK_SIGN, "rotation=2","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_6 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:6"), (short) 3547, Block.DARK_OAK_SIGN, "rotation=3","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_7 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:7"), (short) 3548, Block.DARK_OAK_SIGN, "rotation=3","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_8 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:8"), (short) 3549, Block.DARK_OAK_SIGN, "rotation=4","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_9 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:9"), (short) 3550, Block.DARK_OAK_SIGN, "rotation=4","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_10 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:10"), (short) 3551, Block.DARK_OAK_SIGN, "rotation=5","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_11 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:11"), (short) 3552, Block.DARK_OAK_SIGN, "rotation=5","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_12 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:12"), (short) 3553, Block.DARK_OAK_SIGN, "rotation=6","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_13 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:13"), (short) 3554, Block.DARK_OAK_SIGN, "rotation=6","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_14 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:14"), (short) 3555, Block.DARK_OAK_SIGN, "rotation=7","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_15 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:15"), (short) 3556, Block.DARK_OAK_SIGN, "rotation=7","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_16 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:16"), (short) 3557, Block.DARK_OAK_SIGN, "rotation=8","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_17 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:17"), (short) 3558, Block.DARK_OAK_SIGN, "rotation=8","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_18 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:18"), (short) 3559, Block.DARK_OAK_SIGN, "rotation=9","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_19 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:19"), (short) 3560, Block.DARK_OAK_SIGN, "rotation=9","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_20 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:20"), (short) 3561, Block.DARK_OAK_SIGN, "rotation=10","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_21 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:21"), (short) 3562, Block.DARK_OAK_SIGN, "rotation=10","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_22 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:22"), (short) 3563, Block.DARK_OAK_SIGN, "rotation=11","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_23 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:23"), (short) 3564, Block.DARK_OAK_SIGN, "rotation=11","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_24 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:24"), (short) 3565, Block.DARK_OAK_SIGN, "rotation=12","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_25 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:25"), (short) 3566, Block.DARK_OAK_SIGN, "rotation=12","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_26 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:26"), (short) 3567, Block.DARK_OAK_SIGN, "rotation=13","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_27 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:27"), (short) 3568, Block.DARK_OAK_SIGN, "rotation=13","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_28 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:28"), (short) 3569, Block.DARK_OAK_SIGN, "rotation=14","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_29 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:29"), (short) 3570, Block.DARK_OAK_SIGN, "rotation=14","waterlogged=false");

  public static final BlockState DARK_OAK_SIGN_30 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:30"), (short) 3571, Block.DARK_OAK_SIGN, "rotation=15","waterlogged=true");

  public static final BlockState DARK_OAK_SIGN_31 = new BlockState(NamespaceID.from("minecraft:dark_oak_sign:31"), (short) 3572, Block.DARK_OAK_SIGN, "rotation=15","waterlogged=false");

  public static void initStates() {
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_0);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_1);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_2);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_3);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_4);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_5);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_6);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_7);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_8);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_9);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_10);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_11);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_12);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_13);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_14);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_15);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_16);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_17);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_18);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_19);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_20);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_21);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_22);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_23);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_24);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_25);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_26);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_27);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_28);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_29);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_30);
    Block.DARK_OAK_SIGN.addBlockState(DARK_OAK_SIGN_31);
  }
}
