package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class DarkOakSlab {
  public static void initStates() {
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8334, Block.DARK_OAK_SLAB));
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8335, Block.DARK_OAK_SLAB));
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8336, Block.DARK_OAK_SLAB));
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8337, Block.DARK_OAK_SLAB));
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8338, Block.DARK_OAK_SLAB));
    Block.DARK_OAK_SLAB.addBlockState(new BlockState((short) 8339, Block.DARK_OAK_SLAB));
  }
}
