package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class DarkOakStairs {
	public static void initStates() {
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7459, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7460, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7461, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7462, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7463, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7464, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7465, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7466, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7467, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7468, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7469, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7470, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7471, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7472, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7473, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7474, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7475, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7476, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7477, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7478, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7479, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7480, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7481, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7482, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7483, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7484, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7485, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7486, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7487, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7488, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7489, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7490, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7491, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7492, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7493, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7494, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7495, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7496, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7497, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7498, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7499, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7500, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7501, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7502, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7503, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7504, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7505, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7506, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7507, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7508, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7509, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7510, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7511, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7512, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7513, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7514, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7515, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7516, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7517, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7518, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7519, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7520, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7521, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7522, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7523, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7524, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7525, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7526, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7527, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7528, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7529, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7530, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7531, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7532, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7533, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7534, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7535, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7536, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7537, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7538, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
