package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class DarkOakButton {
    public static void initStates() {
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6470, "face=FLOOR","facing=north","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6471, "face=FLOOR","facing=north","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6472, "face=FLOOR","facing=south","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6473, "face=FLOOR","facing=south","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6474, "face=FLOOR","facing=west","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6475, "face=FLOOR","facing=west","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6476, "face=FLOOR","facing=east","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6477, "face=FLOOR","facing=east","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6478, "face=WALL","facing=north","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6479, "face=WALL","facing=north","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6480, "face=WALL","facing=south","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6481, "face=WALL","facing=south","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6482, "face=WALL","facing=west","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6483, "face=WALL","facing=west","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6484, "face=WALL","facing=east","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6485, "face=WALL","facing=east","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6486, "face=CEILING","facing=north","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6487, "face=CEILING","facing=north","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6488, "face=CEILING","facing=south","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6489, "face=CEILING","facing=south","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6490, "face=CEILING","facing=west","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6491, "face=CEILING","facing=west","powered=false"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6492, "face=CEILING","facing=east","powered=true"));
        Block.DARK_OAK_BUTTON.addBlockAlternative(new BlockAlternative((short) 6493, "face=CEILING","facing=east","powered=false"));
    }
}
