package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class DarkPrismarineStairs {
	public static void initStates() {
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7768, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7769, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7770, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7771, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7772, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7773, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7774, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7775, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7776, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7777, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7778, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7779, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7780, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7781, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7782, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7783, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7784, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7785, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7786, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7787, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7788, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7789, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7790, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7791, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7792, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7793, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7794, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7795, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7796, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7797, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7798, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7799, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7800, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7801, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7802, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7803, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7804, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7805, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7806, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7807, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7808, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7809, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7810, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7811, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7812, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7813, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7814, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7815, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7816, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7817, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7818, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7819, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7820, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7821, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7822, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7823, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7824, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7825, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7826, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7827, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7828, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7829, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7830, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7831, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7832, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7833, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7834, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7835, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7836, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7837, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7838, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7839, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7840, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7841, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7842, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7843, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7844, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7845, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7846, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DARK_PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7847, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
