package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class DeadBubbleCoral {
    public static void initStates() {
        Block.DEAD_BUBBLE_CORAL.addBlockAlternative(new BlockAlternative((short) 9528, "waterlogged=true"));
        Block.DEAD_BUBBLE_CORAL.addBlockAlternative(new BlockAlternative((short) 9529, "waterlogged=false"));
    }
}
