package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class DioriteStairs {
	public static void initStates() {
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10713, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10714, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10715, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10716, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10717, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10718, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10719, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10720, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10721, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10722, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10723, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10724, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10725, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10726, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10727, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10728, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10729, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10730, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10731, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10732, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10733, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10734, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10735, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10736, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10737, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10738, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10739, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10740, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10741, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10742, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10743, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10744, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10745, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10746, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10747, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10748, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10749, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10750, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10751, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10752, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10753, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10754, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10755, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10756, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10757, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10758, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10759, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10760, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10761, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10762, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10763, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10764, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10765, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10766, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10767, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10768, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10769, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10770, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10771, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10772, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10773, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10774, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10775, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10776, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10777, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10778, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10779, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10780, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10781, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10782, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10783, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10784, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10785, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10786, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10787, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10788, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10789, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10790, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10791, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10792, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
