package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class Diorite {
    public static final BlockState DIORITE_0 = new BlockState(NamespaceID.from("minecraft:diorite_0"), (short) 4, Block.DIORITE);

    static {
        Registry.BLOCK_STATE_REGISTRY.register(DIORITE_0);
    }

    public static void initStates() {
        Block.DIORITE.addBlockState(DIORITE_0);
    }
}
