package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class EndRod {
  public static void initStates() {
    Block.END_ROD.addBlockState(new BlockState((short) 9062, Block.END_ROD));
    Block.END_ROD.addBlockState(new BlockState((short) 9063, Block.END_ROD));
    Block.END_ROD.addBlockState(new BlockState((short) 9064, Block.END_ROD));
    Block.END_ROD.addBlockState(new BlockState((short) 9065, Block.END_ROD));
    Block.END_ROD.addBlockState(new BlockState((short) 9066, Block.END_ROD));
    Block.END_ROD.addBlockState(new BlockState((short) 9067, Block.END_ROD));
  }
}
