package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class EndStoneBrickStairs {
	public static void initStates() {
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10073, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10074, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10075, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10076, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10077, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10078, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10079, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10080, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10081, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10082, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10083, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10084, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10085, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10086, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10087, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10088, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10089, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10090, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10091, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10092, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10093, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10094, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10095, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10096, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10097, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10098, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10099, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10100, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10101, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10102, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10103, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10104, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10105, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10106, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10107, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10108, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10109, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10110, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10111, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10112, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10113, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10114, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10115, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10116, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10117, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10118, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10119, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10120, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10121, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10122, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10123, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10124, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10125, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10126, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10127, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10128, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10129, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10130, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10131, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10132, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10133, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10134, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10135, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10136, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10137, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10138, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10139, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10140, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10141, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10142, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10143, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10144, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10145, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10146, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10147, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10148, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10149, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10150, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10151, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		END_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10152, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
