package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class FlowerPot {
    public static final BlockState FLOWER_POT_0 = new BlockState(NamespaceID.from("minecraft:flower_pot_0"), (short) 6309, Block.FLOWER_POT, new RawBlockStateData(0.0, 0, false, "DESTROY", false, false, false, false, false, false, 0, "[AABB[0.3125, 0.0, 0.3125] -> [0.6875, 0.375, 0.6875]]"));

    static {
        Registry.BLOCK_STATE_REGISTRY.register(FLOWER_POT_0);
    }

    public static void initStates() {
        Block.FLOWER_POT.addBlockState(FLOWER_POT_0);
    }
}
