package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class FrostedIce {
  public static void initStates() {
    Block.FROSTED_ICE.addBlockState(new BlockState((short) 9253, Block.FROSTED_ICE));
    Block.FROSTED_ICE.addBlockState(new BlockState((short) 9254, Block.FROSTED_ICE));
    Block.FROSTED_ICE.addBlockState(new BlockState((short) 9255, Block.FROSTED_ICE));
    Block.FROSTED_ICE.addBlockState(new BlockState((short) 9256, Block.FROSTED_ICE));
  }
}
