package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class GoldBlock {
  public static void initStates() {
    Block.GOLD_BLOCK.addBlockState(new BlockState((short) 1427, Block.GOLD_BLOCK));
  }
}
