package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class GrassBlock {
    public static void initStates() {
        Block.GRASS_BLOCK.addBlockAlternative(new BlockAlternative((short) 8, "snowy=true"));
        Block.GRASS_BLOCK.addBlockAlternative(new BlockAlternative((short) 9, "snowy=false"));
    }
}
