package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Gravel {
  public static final BlockState GRAVEL_0 = new BlockState(NamespaceID.from("minecraft:gravel_0"), (short) 68, Block.GRAVEL);

  static {
    Registries.registerBlockState(GRAVEL_0);
  }

  public static void initStates() {
    Block.GRAVEL.addBlockState(GRAVEL_0);
  }
}
