package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class GrayBed {
    public static final BlockState GRAY_BED_0 = new BlockState(NamespaceID.from("minecraft:gray_bed_0"), (short) 1161, Block.GRAY_BED, "facing=north","occupied=true","part=head");

    public static final BlockState GRAY_BED_1 = new BlockState(NamespaceID.from("minecraft:gray_bed_1"), (short) 1162, Block.GRAY_BED, "facing=north","occupied=true","part=foot");

    public static final BlockState GRAY_BED_2 = new BlockState(NamespaceID.from("minecraft:gray_bed_2"), (short) 1163, Block.GRAY_BED, "facing=north","occupied=false","part=head");

    public static final BlockState GRAY_BED_3 = new BlockState(NamespaceID.from("minecraft:gray_bed_3"), (short) 1164, Block.GRAY_BED, "facing=north","occupied=false","part=foot");

    public static final BlockState GRAY_BED_4 = new BlockState(NamespaceID.from("minecraft:gray_bed_4"), (short) 1165, Block.GRAY_BED, "facing=south","occupied=true","part=head");

    public static final BlockState GRAY_BED_5 = new BlockState(NamespaceID.from("minecraft:gray_bed_5"), (short) 1166, Block.GRAY_BED, "facing=south","occupied=true","part=foot");

    public static final BlockState GRAY_BED_6 = new BlockState(NamespaceID.from("minecraft:gray_bed_6"), (short) 1167, Block.GRAY_BED, "facing=south","occupied=false","part=head");

    public static final BlockState GRAY_BED_7 = new BlockState(NamespaceID.from("minecraft:gray_bed_7"), (short) 1168, Block.GRAY_BED, "facing=south","occupied=false","part=foot");

    public static final BlockState GRAY_BED_8 = new BlockState(NamespaceID.from("minecraft:gray_bed_8"), (short) 1169, Block.GRAY_BED, "facing=west","occupied=true","part=head");

    public static final BlockState GRAY_BED_9 = new BlockState(NamespaceID.from("minecraft:gray_bed_9"), (short) 1170, Block.GRAY_BED, "facing=west","occupied=true","part=foot");

    public static final BlockState GRAY_BED_10 = new BlockState(NamespaceID.from("minecraft:gray_bed_10"), (short) 1171, Block.GRAY_BED, "facing=west","occupied=false","part=head");

    public static final BlockState GRAY_BED_11 = new BlockState(NamespaceID.from("minecraft:gray_bed_11"), (short) 1172, Block.GRAY_BED, "facing=west","occupied=false","part=foot");

    public static final BlockState GRAY_BED_12 = new BlockState(NamespaceID.from("minecraft:gray_bed_12"), (short) 1173, Block.GRAY_BED, "facing=east","occupied=true","part=head");

    public static final BlockState GRAY_BED_13 = new BlockState(NamespaceID.from("minecraft:gray_bed_13"), (short) 1174, Block.GRAY_BED, "facing=east","occupied=true","part=foot");

    public static final BlockState GRAY_BED_14 = new BlockState(NamespaceID.from("minecraft:gray_bed_14"), (short) 1175, Block.GRAY_BED, "facing=east","occupied=false","part=head");

    public static final BlockState GRAY_BED_15 = new BlockState(NamespaceID.from("minecraft:gray_bed_15"), (short) 1176, Block.GRAY_BED, "facing=east","occupied=false","part=foot");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_0);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_1);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_2);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_3);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_4);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_5);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_6);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_7);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_8);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_9);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_10);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_11);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_12);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_13);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_14);
        Registry.BLOCK_STATE_REGISTRY.register(GRAY_BED_15);
    }

    public static void initStates() {
        Block.GRAY_BED.addBlockState(GRAY_BED_0);
        Block.GRAY_BED.addBlockState(GRAY_BED_1);
        Block.GRAY_BED.addBlockState(GRAY_BED_2);
        Block.GRAY_BED.addBlockState(GRAY_BED_3);
        Block.GRAY_BED.addBlockState(GRAY_BED_4);
        Block.GRAY_BED.addBlockState(GRAY_BED_5);
        Block.GRAY_BED.addBlockState(GRAY_BED_6);
        Block.GRAY_BED.addBlockState(GRAY_BED_7);
        Block.GRAY_BED.addBlockState(GRAY_BED_8);
        Block.GRAY_BED.addBlockState(GRAY_BED_9);
        Block.GRAY_BED.addBlockState(GRAY_BED_10);
        Block.GRAY_BED.addBlockState(GRAY_BED_11);
        Block.GRAY_BED.addBlockState(GRAY_BED_12);
        Block.GRAY_BED.addBlockState(GRAY_BED_13);
        Block.GRAY_BED.addBlockState(GRAY_BED_14);
        Block.GRAY_BED.addBlockState(GRAY_BED_15);
    }
}
