package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class GreenBed {
    public static final BlockState GREEN_BED_0 = new BlockState(NamespaceID.from("minecraft:green_bed_0"), (short) 1257, Block.GREEN_BED, "facing=north","occupied=true","part=head");

    public static final BlockState GREEN_BED_1 = new BlockState(NamespaceID.from("minecraft:green_bed_1"), (short) 1258, Block.GREEN_BED, "facing=north","occupied=true","part=foot");

    public static final BlockState GREEN_BED_2 = new BlockState(NamespaceID.from("minecraft:green_bed_2"), (short) 1259, Block.GREEN_BED, "facing=north","occupied=false","part=head");

    public static final BlockState GREEN_BED_3 = new BlockState(NamespaceID.from("minecraft:green_bed_3"), (short) 1260, Block.GREEN_BED, "facing=north","occupied=false","part=foot");

    public static final BlockState GREEN_BED_4 = new BlockState(NamespaceID.from("minecraft:green_bed_4"), (short) 1261, Block.GREEN_BED, "facing=south","occupied=true","part=head");

    public static final BlockState GREEN_BED_5 = new BlockState(NamespaceID.from("minecraft:green_bed_5"), (short) 1262, Block.GREEN_BED, "facing=south","occupied=true","part=foot");

    public static final BlockState GREEN_BED_6 = new BlockState(NamespaceID.from("minecraft:green_bed_6"), (short) 1263, Block.GREEN_BED, "facing=south","occupied=false","part=head");

    public static final BlockState GREEN_BED_7 = new BlockState(NamespaceID.from("minecraft:green_bed_7"), (short) 1264, Block.GREEN_BED, "facing=south","occupied=false","part=foot");

    public static final BlockState GREEN_BED_8 = new BlockState(NamespaceID.from("minecraft:green_bed_8"), (short) 1265, Block.GREEN_BED, "facing=west","occupied=true","part=head");

    public static final BlockState GREEN_BED_9 = new BlockState(NamespaceID.from("minecraft:green_bed_9"), (short) 1266, Block.GREEN_BED, "facing=west","occupied=true","part=foot");

    public static final BlockState GREEN_BED_10 = new BlockState(NamespaceID.from("minecraft:green_bed_10"), (short) 1267, Block.GREEN_BED, "facing=west","occupied=false","part=head");

    public static final BlockState GREEN_BED_11 = new BlockState(NamespaceID.from("minecraft:green_bed_11"), (short) 1268, Block.GREEN_BED, "facing=west","occupied=false","part=foot");

    public static final BlockState GREEN_BED_12 = new BlockState(NamespaceID.from("minecraft:green_bed_12"), (short) 1269, Block.GREEN_BED, "facing=east","occupied=true","part=head");

    public static final BlockState GREEN_BED_13 = new BlockState(NamespaceID.from("minecraft:green_bed_13"), (short) 1270, Block.GREEN_BED, "facing=east","occupied=true","part=foot");

    public static final BlockState GREEN_BED_14 = new BlockState(NamespaceID.from("minecraft:green_bed_14"), (short) 1271, Block.GREEN_BED, "facing=east","occupied=false","part=head");

    public static final BlockState GREEN_BED_15 = new BlockState(NamespaceID.from("minecraft:green_bed_15"), (short) 1272, Block.GREEN_BED, "facing=east","occupied=false","part=foot");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_0);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_1);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_2);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_3);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_4);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_5);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_6);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_7);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_8);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_9);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_10);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_11);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_12);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_13);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_14);
        Registry.BLOCK_STATE_REGISTRY.register(GREEN_BED_15);
    }

    public static void initStates() {
        Block.GREEN_BED.addBlockState(GREEN_BED_0);
        Block.GREEN_BED.addBlockState(GREEN_BED_1);
        Block.GREEN_BED.addBlockState(GREEN_BED_2);
        Block.GREEN_BED.addBlockState(GREEN_BED_3);
        Block.GREEN_BED.addBlockState(GREEN_BED_4);
        Block.GREEN_BED.addBlockState(GREEN_BED_5);
        Block.GREEN_BED.addBlockState(GREEN_BED_6);
        Block.GREEN_BED.addBlockState(GREEN_BED_7);
        Block.GREEN_BED.addBlockState(GREEN_BED_8);
        Block.GREEN_BED.addBlockState(GREEN_BED_9);
        Block.GREEN_BED.addBlockState(GREEN_BED_10);
        Block.GREEN_BED.addBlockState(GREEN_BED_11);
        Block.GREEN_BED.addBlockState(GREEN_BED_12);
        Block.GREEN_BED.addBlockState(GREEN_BED_13);
        Block.GREEN_BED.addBlockState(GREEN_BED_14);
        Block.GREEN_BED.addBlockState(GREEN_BED_15);
    }
}
