package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class GreenConcrete {
    public static void initStates() {
        Block.GREEN_CONCRETE.addBlockAlternative(new BlockAlternative((short) 9455));
    }
}
