package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class InfestedMossyStoneBricks {
    public static void initStates() {
        Block.INFESTED_MOSSY_STONE_BRICKS.addBlockAlternative(new BlockAlternative((short) 4502));
    }
}
