package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class IronBars {
  public static void initStates() {
    Block.IRON_BARS.addBlockState(new BlockState((short) 4697, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4698, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4699, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4700, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4701, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4702, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4703, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4704, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4705, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4706, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4707, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4708, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4709, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4710, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4711, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4712, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4713, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4714, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4715, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4716, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4717, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4718, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4719, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4720, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4721, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4722, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4723, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4724, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4725, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4726, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4727, Block.IRON_BARS));
    Block.IRON_BARS.addBlockState(new BlockState((short) 4728, Block.IRON_BARS));
  }
}
