package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class JungleStairs {
	public static void initStates() {
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5568, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5569, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5570, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5571, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5572, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5573, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5574, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5575, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5576, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5577, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5578, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5579, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5580, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5581, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5582, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5583, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5584, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5585, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5586, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5587, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5588, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5589, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5590, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5591, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5592, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5593, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5594, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5595, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5596, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5597, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5598, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5599, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5600, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5601, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5602, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5603, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5604, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5605, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5606, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5607, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5608, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5609, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5610, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5611, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5612, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5613, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5614, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5615, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5616, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5617, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5618, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5619, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5620, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5621, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5622, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5623, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5624, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5625, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5626, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5627, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5628, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5629, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5630, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5631, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5632, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5633, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5634, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5635, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5636, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5637, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5638, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5639, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5640, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5641, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5642, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5643, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5644, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5645, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5646, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		JUNGLE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5647, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
