package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class JungleStairs {
  public static void initStates() {
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5568, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5569, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5570, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5571, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5572, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5573, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5574, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5575, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5576, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5577, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5578, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5579, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5580, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5581, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5582, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5583, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5584, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5585, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5586, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5587, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5588, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5589, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5590, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5591, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5592, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5593, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5594, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5595, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5596, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5597, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5598, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5599, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5600, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5601, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5602, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5603, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5604, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5605, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5606, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5607, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5608, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5609, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5610, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5611, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5612, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5613, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5614, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5615, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5616, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5617, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5618, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5619, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5620, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5621, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5622, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5623, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5624, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5625, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5626, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5627, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5628, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5629, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5630, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5631, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5632, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5633, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5634, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5635, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5636, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5637, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5638, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5639, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5640, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5641, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5642, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5643, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5644, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5645, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5646, Block.JUNGLE_STAIRS));
    Block.JUNGLE_STAIRS.addBlockState(new BlockState((short) 5647, Block.JUNGLE_STAIRS));
  }
}
