package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.raw_data.RawBlockStateData;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class LargeFern {
    public static final BlockState LARGE_FERN_0 = new BlockState(NamespaceID.from("minecraft:large_fern_0"), (short) 7899, Block.LARGE_FERN, new RawBlockStateData(0.0, 0, false, "DESTROY", false, true, false, true, false, false, 7, "[]"), "half=upper");

    public static final BlockState LARGE_FERN_1 = new BlockState(NamespaceID.from("minecraft:large_fern_1"), (short) 7900, Block.LARGE_FERN, new RawBlockStateData(0.0, 0, false, "DESTROY", false, true, false, true, false, false, 7, "[]"), "half=lower");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(LARGE_FERN_0);
        Registry.BLOCK_STATE_REGISTRY.register(LARGE_FERN_1);
    }

    public static void initStates() {
        Block.LARGE_FERN.addBlockState(LARGE_FERN_0);
        Block.LARGE_FERN.addBlockState(LARGE_FERN_1);
    }
}
