package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Lectern {
  public static final BlockState LECTERN_0 = new BlockState(NamespaceID.from("minecraft:lectern_0"), (short) 14837, Block.LECTERN, "facing=north","has_book=true","powered=true");

  public static final BlockState LECTERN_1 = new BlockState(NamespaceID.from("minecraft:lectern_1"), (short) 14838, Block.LECTERN, "facing=north","has_book=true","powered=false");

  public static final BlockState LECTERN_2 = new BlockState(NamespaceID.from("minecraft:lectern_2"), (short) 14839, Block.LECTERN, "facing=north","has_book=false","powered=true");

  public static final BlockState LECTERN_3 = new BlockState(NamespaceID.from("minecraft:lectern_3"), (short) 14840, Block.LECTERN, "facing=north","has_book=false","powered=false");

  public static final BlockState LECTERN_4 = new BlockState(NamespaceID.from("minecraft:lectern_4"), (short) 14841, Block.LECTERN, "facing=south","has_book=true","powered=true");

  public static final BlockState LECTERN_5 = new BlockState(NamespaceID.from("minecraft:lectern_5"), (short) 14842, Block.LECTERN, "facing=south","has_book=true","powered=false");

  public static final BlockState LECTERN_6 = new BlockState(NamespaceID.from("minecraft:lectern_6"), (short) 14843, Block.LECTERN, "facing=south","has_book=false","powered=true");

  public static final BlockState LECTERN_7 = new BlockState(NamespaceID.from("minecraft:lectern_7"), (short) 14844, Block.LECTERN, "facing=south","has_book=false","powered=false");

  public static final BlockState LECTERN_8 = new BlockState(NamespaceID.from("minecraft:lectern_8"), (short) 14845, Block.LECTERN, "facing=west","has_book=true","powered=true");

  public static final BlockState LECTERN_9 = new BlockState(NamespaceID.from("minecraft:lectern_9"), (short) 14846, Block.LECTERN, "facing=west","has_book=true","powered=false");

  public static final BlockState LECTERN_10 = new BlockState(NamespaceID.from("minecraft:lectern_10"), (short) 14847, Block.LECTERN, "facing=west","has_book=false","powered=true");

  public static final BlockState LECTERN_11 = new BlockState(NamespaceID.from("minecraft:lectern_11"), (short) 14848, Block.LECTERN, "facing=west","has_book=false","powered=false");

  public static final BlockState LECTERN_12 = new BlockState(NamespaceID.from("minecraft:lectern_12"), (short) 14849, Block.LECTERN, "facing=east","has_book=true","powered=true");

  public static final BlockState LECTERN_13 = new BlockState(NamespaceID.from("minecraft:lectern_13"), (short) 14850, Block.LECTERN, "facing=east","has_book=true","powered=false");

  public static final BlockState LECTERN_14 = new BlockState(NamespaceID.from("minecraft:lectern_14"), (short) 14851, Block.LECTERN, "facing=east","has_book=false","powered=true");

  public static final BlockState LECTERN_15 = new BlockState(NamespaceID.from("minecraft:lectern_15"), (short) 14852, Block.LECTERN, "facing=east","has_book=false","powered=false");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_0);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_1);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_2);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_3);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_4);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_5);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_6);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_7);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_8);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_9);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_10);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_11);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_12);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_13);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_14);
    Registry.BLOCK_STATE_REGISTRY.register(LECTERN_15);
  }

  public static void initStates() {
    Block.LECTERN.addBlockState(LECTERN_0);
    Block.LECTERN.addBlockState(LECTERN_1);
    Block.LECTERN.addBlockState(LECTERN_2);
    Block.LECTERN.addBlockState(LECTERN_3);
    Block.LECTERN.addBlockState(LECTERN_4);
    Block.LECTERN.addBlockState(LECTERN_5);
    Block.LECTERN.addBlockState(LECTERN_6);
    Block.LECTERN.addBlockState(LECTERN_7);
    Block.LECTERN.addBlockState(LECTERN_8);
    Block.LECTERN.addBlockState(LECTERN_9);
    Block.LECTERN.addBlockState(LECTERN_10);
    Block.LECTERN.addBlockState(LECTERN_11);
    Block.LECTERN.addBlockState(LECTERN_12);
    Block.LECTERN.addBlockState(LECTERN_13);
    Block.LECTERN.addBlockState(LECTERN_14);
    Block.LECTERN.addBlockState(LECTERN_15);
  }
}
