package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class LightBlueCarpet {
  public static final BlockState LIGHT_BLUE_CARPET_0 = new BlockState(NamespaceID.from("minecraft:light_blue_carpet:0"), (short) 7873, Block.LIGHT_BLUE_CARPET);

  static {
    Registries.registerBlockState(LIGHT_BLUE_CARPET_0);
  }

  public static void initStates() {
    Block.LIGHT_BLUE_CARPET.addBlockState(LIGHT_BLUE_CARPET_0);
  }
}
