package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class LightBlueBanner {
  public static void initStates() {
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7949, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7950, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7951, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7952, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7953, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7954, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7955, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7956, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7957, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7958, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7959, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7960, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7961, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7962, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7963, Block.LIGHT_BLUE_BANNER));
    Block.LIGHT_BLUE_BANNER.addBlockState(new BlockState((short) 7964, Block.LIGHT_BLUE_BANNER));
  }
}
