package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class LightBlueBanner {
  public static final BlockState LIGHT_BLUE_BANNER_0 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_0"), (short) 7949, Block.LIGHT_BLUE_BANNER, "rotation=0");

  public static final BlockState LIGHT_BLUE_BANNER_1 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_1"), (short) 7950, Block.LIGHT_BLUE_BANNER, "rotation=1");

  public static final BlockState LIGHT_BLUE_BANNER_2 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_2"), (short) 7951, Block.LIGHT_BLUE_BANNER, "rotation=2");

  public static final BlockState LIGHT_BLUE_BANNER_3 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_3"), (short) 7952, Block.LIGHT_BLUE_BANNER, "rotation=3");

  public static final BlockState LIGHT_BLUE_BANNER_4 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_4"), (short) 7953, Block.LIGHT_BLUE_BANNER, "rotation=4");

  public static final BlockState LIGHT_BLUE_BANNER_5 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_5"), (short) 7954, Block.LIGHT_BLUE_BANNER, "rotation=5");

  public static final BlockState LIGHT_BLUE_BANNER_6 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_6"), (short) 7955, Block.LIGHT_BLUE_BANNER, "rotation=6");

  public static final BlockState LIGHT_BLUE_BANNER_7 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_7"), (short) 7956, Block.LIGHT_BLUE_BANNER, "rotation=7");

  public static final BlockState LIGHT_BLUE_BANNER_8 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_8"), (short) 7957, Block.LIGHT_BLUE_BANNER, "rotation=8");

  public static final BlockState LIGHT_BLUE_BANNER_9 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_9"), (short) 7958, Block.LIGHT_BLUE_BANNER, "rotation=9");

  public static final BlockState LIGHT_BLUE_BANNER_10 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_10"), (short) 7959, Block.LIGHT_BLUE_BANNER, "rotation=10");

  public static final BlockState LIGHT_BLUE_BANNER_11 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_11"), (short) 7960, Block.LIGHT_BLUE_BANNER, "rotation=11");

  public static final BlockState LIGHT_BLUE_BANNER_12 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_12"), (short) 7961, Block.LIGHT_BLUE_BANNER, "rotation=12");

  public static final BlockState LIGHT_BLUE_BANNER_13 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_13"), (short) 7962, Block.LIGHT_BLUE_BANNER, "rotation=13");

  public static final BlockState LIGHT_BLUE_BANNER_14 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_14"), (short) 7963, Block.LIGHT_BLUE_BANNER, "rotation=14");

  public static final BlockState LIGHT_BLUE_BANNER_15 = new BlockState(NamespaceID.from("minecraft:light_blue_banner_15"), (short) 7964, Block.LIGHT_BLUE_BANNER, "rotation=15");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_0);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_1);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_2);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_3);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_4);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_5);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_6);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_7);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_8);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_9);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_10);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_11);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_12);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_13);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_14);
    Registry.BLOCK_STATE_REGISTRY.register(LIGHT_BLUE_BANNER_15);
  }

  public static void initStates() {
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_0);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_1);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_2);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_3);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_4);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_5);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_6);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_7);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_8);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_9);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_10);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_11);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_12);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_13);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_14);
    Block.LIGHT_BLUE_BANNER.addBlockState(LIGHT_BLUE_BANNER_15);
  }
}
