package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class LightBlueConcrete {
  public static void initStates() {
    Block.LIGHT_BLUE_CONCRETE.addBlockState(new BlockState((short) 9445, Block.LIGHT_BLUE_CONCRETE));
  }
}
