package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Lilac {
  public static void initStates() {
    Block.LILAC.addBlockState(new BlockState((short) 7891, Block.LILAC));
    Block.LILAC.addBlockState(new BlockState((short) 7892, Block.LILAC));
  }
}
