package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class LilyPad {
  public static final BlockState LILY_PAD_0 = new BlockState(NamespaceID.from("minecraft:lily_pad:0"), (short) 5018, Block.LILY_PAD);

  static {
    Registries.registerBlockState(LILY_PAD_0);
  }

  public static void initStates() {
    Block.LILY_PAD.addBlockState(LILY_PAD_0);
  }
}
