package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class MossyCobblestoneStairs {
	public static void initStates() {
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9453, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9454, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9455, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9456, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9457, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9458, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9459, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9460, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9461, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9462, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9463, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9464, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9465, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9466, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9467, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9468, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9469, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9470, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9471, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9472, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9473, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9474, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9475, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9476, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9477, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9478, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9479, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9480, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9481, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9482, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9483, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9484, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9485, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9486, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9487, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9488, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9489, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9490, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9491, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9492, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9493, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9494, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9495, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9496, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9497, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9498, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9499, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9500, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9501, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9502, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9503, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9504, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9505, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9506, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9507, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9508, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9509, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9510, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9511, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9512, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9513, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9514, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9515, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9516, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9517, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9518, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9519, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9520, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9521, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9522, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9523, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9524, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9525, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9526, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9527, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9528, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9529, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9530, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9531, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9532, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
