package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class MossyCobblestoneStairs {
	public static void initStates() {
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9993, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9994, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9995, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9996, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9997, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9998, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9999, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10000, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10001, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10002, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10003, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10004, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10005, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10006, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10007, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10008, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10009, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10010, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10011, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10012, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10013, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10014, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10015, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10016, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10017, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10018, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10019, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10020, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10021, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10022, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10023, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10024, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10025, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10026, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10027, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10028, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10029, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10030, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10031, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10032, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10033, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10034, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10035, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10036, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10037, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10038, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10039, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10040, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10041, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10042, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10043, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10044, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10045, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10046, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10047, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10048, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10049, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10050, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10051, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10052, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10053, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10054, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10055, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10056, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10057, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10058, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10059, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10060, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10061, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10062, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10063, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10064, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10065, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10066, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10067, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10068, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10069, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10070, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10071, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_COBBLESTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10072, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
