package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class MossyStoneBrickStairs {
	public static void initStates() {
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9833, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9834, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9835, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9836, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9837, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9838, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9839, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9840, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9841, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9842, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9843, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9844, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9845, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9846, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9847, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9848, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9849, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9850, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9851, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9852, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9853, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9854, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9855, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9856, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9857, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9858, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9859, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9860, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9861, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9862, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9863, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9864, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9865, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9866, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9867, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9868, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9869, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9870, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9871, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9872, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9873, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9874, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9875, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9876, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9877, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9878, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9879, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9880, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9881, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9882, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9883, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9884, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9885, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9886, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9887, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9888, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9889, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9890, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9891, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9892, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9893, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9894, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9895, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9896, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9897, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9898, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9899, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9900, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9901, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9902, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9903, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9904, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9905, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9906, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9907, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9908, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9909, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9910, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9911, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9912, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
