package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class NetherGoldOre {
  public static void initStates() {
    Block.NETHER_GOLD_ORE.addBlockState(new BlockState((short) 72, Block.NETHER_GOLD_ORE));
  }
}
