package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class NetherBrickStairs {
	public static void initStates() {
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5052, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5053, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5054, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5055, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5056, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5057, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5058, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5059, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5060, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5061, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5062, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5063, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5064, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5065, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5066, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5067, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5068, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5069, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5070, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5071, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5072, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5073, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5074, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5075, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5076, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5077, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5078, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5079, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5080, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5081, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5082, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5083, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5084, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5085, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5086, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5087, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5088, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5089, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5090, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5091, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5092, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5093, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5094, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5095, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5096, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5097, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5098, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5099, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5100, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5101, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5102, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5103, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5104, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5105, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5106, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5107, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5108, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5109, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5110, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5111, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5112, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5113, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5114, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5115, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5116, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5117, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5118, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5119, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5120, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5121, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5122, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5123, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5124, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5125, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5126, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5127, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5128, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5129, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5130, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5131, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
