package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class NetherWartBlock {
  public static final BlockState NETHER_WART_BLOCK_0 = new BlockState(NamespaceID.from("minecraft:nether_wart_block_0"), (short) 9258, Block.NETHER_WART_BLOCK);

  static {
    Registry.BLOCK_STATE_REGISTRY.register(NETHER_WART_BLOCK_0);
  }

  public static void initStates() {
    Block.NETHER_WART_BLOCK.addBlockState(NETHER_WART_BLOCK_0);
  }
}
