package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class OakLog {
  public static void initStates() {
    Block.OAK_LOG.addBlockState(new BlockState((short) 73, Block.OAK_LOG));
    Block.OAK_LOG.addBlockState(new BlockState((short) 74, Block.OAK_LOG));
    Block.OAK_LOG.addBlockState(new BlockState((short) 75, Block.OAK_LOG));
  }
}
