package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class OakStairs {
  public static final BlockState OAK_STAIRS_0 = new BlockState(NamespaceID.from("minecraft:oak_stairs_0"), (short) 1954, Block.OAK_STAIRS, "facing=north","half=top","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_1 = new BlockState(NamespaceID.from("minecraft:oak_stairs_1"), (short) 1955, Block.OAK_STAIRS, "facing=north","half=top","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_2 = new BlockState(NamespaceID.from("minecraft:oak_stairs_2"), (short) 1956, Block.OAK_STAIRS, "facing=north","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_3 = new BlockState(NamespaceID.from("minecraft:oak_stairs_3"), (short) 1957, Block.OAK_STAIRS, "facing=north","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_4 = new BlockState(NamespaceID.from("minecraft:oak_stairs_4"), (short) 1958, Block.OAK_STAIRS, "facing=north","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_5 = new BlockState(NamespaceID.from("minecraft:oak_stairs_5"), (short) 1959, Block.OAK_STAIRS, "facing=north","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_6 = new BlockState(NamespaceID.from("minecraft:oak_stairs_6"), (short) 1960, Block.OAK_STAIRS, "facing=north","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_7 = new BlockState(NamespaceID.from("minecraft:oak_stairs_7"), (short) 1961, Block.OAK_STAIRS, "facing=north","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_8 = new BlockState(NamespaceID.from("minecraft:oak_stairs_8"), (short) 1962, Block.OAK_STAIRS, "facing=north","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_9 = new BlockState(NamespaceID.from("minecraft:oak_stairs_9"), (short) 1963, Block.OAK_STAIRS, "facing=north","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_10 = new BlockState(NamespaceID.from("minecraft:oak_stairs_10"), (short) 1964, Block.OAK_STAIRS, "facing=north","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_11 = new BlockState(NamespaceID.from("minecraft:oak_stairs_11"), (short) 1965, Block.OAK_STAIRS, "facing=north","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_12 = new BlockState(NamespaceID.from("minecraft:oak_stairs_12"), (short) 1966, Block.OAK_STAIRS, "facing=north","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_13 = new BlockState(NamespaceID.from("minecraft:oak_stairs_13"), (short) 1967, Block.OAK_STAIRS, "facing=north","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_14 = new BlockState(NamespaceID.from("minecraft:oak_stairs_14"), (short) 1968, Block.OAK_STAIRS, "facing=north","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_15 = new BlockState(NamespaceID.from("minecraft:oak_stairs_15"), (short) 1969, Block.OAK_STAIRS, "facing=north","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_16 = new BlockState(NamespaceID.from("minecraft:oak_stairs_16"), (short) 1970, Block.OAK_STAIRS, "facing=north","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_17 = new BlockState(NamespaceID.from("minecraft:oak_stairs_17"), (short) 1971, Block.OAK_STAIRS, "facing=north","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_18 = new BlockState(NamespaceID.from("minecraft:oak_stairs_18"), (short) 1972, Block.OAK_STAIRS, "facing=north","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_19 = new BlockState(NamespaceID.from("minecraft:oak_stairs_19"), (short) 1973, Block.OAK_STAIRS, "facing=north","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_20 = new BlockState(NamespaceID.from("minecraft:oak_stairs_20"), (short) 1974, Block.OAK_STAIRS, "facing=south","half=top","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_21 = new BlockState(NamespaceID.from("minecraft:oak_stairs_21"), (short) 1975, Block.OAK_STAIRS, "facing=south","half=top","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_22 = new BlockState(NamespaceID.from("minecraft:oak_stairs_22"), (short) 1976, Block.OAK_STAIRS, "facing=south","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_23 = new BlockState(NamespaceID.from("minecraft:oak_stairs_23"), (short) 1977, Block.OAK_STAIRS, "facing=south","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_24 = new BlockState(NamespaceID.from("minecraft:oak_stairs_24"), (short) 1978, Block.OAK_STAIRS, "facing=south","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_25 = new BlockState(NamespaceID.from("minecraft:oak_stairs_25"), (short) 1979, Block.OAK_STAIRS, "facing=south","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_26 = new BlockState(NamespaceID.from("minecraft:oak_stairs_26"), (short) 1980, Block.OAK_STAIRS, "facing=south","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_27 = new BlockState(NamespaceID.from("minecraft:oak_stairs_27"), (short) 1981, Block.OAK_STAIRS, "facing=south","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_28 = new BlockState(NamespaceID.from("minecraft:oak_stairs_28"), (short) 1982, Block.OAK_STAIRS, "facing=south","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_29 = new BlockState(NamespaceID.from("minecraft:oak_stairs_29"), (short) 1983, Block.OAK_STAIRS, "facing=south","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_30 = new BlockState(NamespaceID.from("minecraft:oak_stairs_30"), (short) 1984, Block.OAK_STAIRS, "facing=south","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_31 = new BlockState(NamespaceID.from("minecraft:oak_stairs_31"), (short) 1985, Block.OAK_STAIRS, "facing=south","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_32 = new BlockState(NamespaceID.from("minecraft:oak_stairs_32"), (short) 1986, Block.OAK_STAIRS, "facing=south","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_33 = new BlockState(NamespaceID.from("minecraft:oak_stairs_33"), (short) 1987, Block.OAK_STAIRS, "facing=south","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_34 = new BlockState(NamespaceID.from("minecraft:oak_stairs_34"), (short) 1988, Block.OAK_STAIRS, "facing=south","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_35 = new BlockState(NamespaceID.from("minecraft:oak_stairs_35"), (short) 1989, Block.OAK_STAIRS, "facing=south","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_36 = new BlockState(NamespaceID.from("minecraft:oak_stairs_36"), (short) 1990, Block.OAK_STAIRS, "facing=south","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_37 = new BlockState(NamespaceID.from("minecraft:oak_stairs_37"), (short) 1991, Block.OAK_STAIRS, "facing=south","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_38 = new BlockState(NamespaceID.from("minecraft:oak_stairs_38"), (short) 1992, Block.OAK_STAIRS, "facing=south","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_39 = new BlockState(NamespaceID.from("minecraft:oak_stairs_39"), (short) 1993, Block.OAK_STAIRS, "facing=south","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_40 = new BlockState(NamespaceID.from("minecraft:oak_stairs_40"), (short) 1994, Block.OAK_STAIRS, "facing=west","half=top","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_41 = new BlockState(NamespaceID.from("minecraft:oak_stairs_41"), (short) 1995, Block.OAK_STAIRS, "facing=west","half=top","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_42 = new BlockState(NamespaceID.from("minecraft:oak_stairs_42"), (short) 1996, Block.OAK_STAIRS, "facing=west","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_43 = new BlockState(NamespaceID.from("minecraft:oak_stairs_43"), (short) 1997, Block.OAK_STAIRS, "facing=west","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_44 = new BlockState(NamespaceID.from("minecraft:oak_stairs_44"), (short) 1998, Block.OAK_STAIRS, "facing=west","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_45 = new BlockState(NamespaceID.from("minecraft:oak_stairs_45"), (short) 1999, Block.OAK_STAIRS, "facing=west","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_46 = new BlockState(NamespaceID.from("minecraft:oak_stairs_46"), (short) 2000, Block.OAK_STAIRS, "facing=west","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_47 = new BlockState(NamespaceID.from("minecraft:oak_stairs_47"), (short) 2001, Block.OAK_STAIRS, "facing=west","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_48 = new BlockState(NamespaceID.from("minecraft:oak_stairs_48"), (short) 2002, Block.OAK_STAIRS, "facing=west","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_49 = new BlockState(NamespaceID.from("minecraft:oak_stairs_49"), (short) 2003, Block.OAK_STAIRS, "facing=west","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_50 = new BlockState(NamespaceID.from("minecraft:oak_stairs_50"), (short) 2004, Block.OAK_STAIRS, "facing=west","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_51 = new BlockState(NamespaceID.from("minecraft:oak_stairs_51"), (short) 2005, Block.OAK_STAIRS, "facing=west","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_52 = new BlockState(NamespaceID.from("minecraft:oak_stairs_52"), (short) 2006, Block.OAK_STAIRS, "facing=west","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_53 = new BlockState(NamespaceID.from("minecraft:oak_stairs_53"), (short) 2007, Block.OAK_STAIRS, "facing=west","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_54 = new BlockState(NamespaceID.from("minecraft:oak_stairs_54"), (short) 2008, Block.OAK_STAIRS, "facing=west","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_55 = new BlockState(NamespaceID.from("minecraft:oak_stairs_55"), (short) 2009, Block.OAK_STAIRS, "facing=west","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_56 = new BlockState(NamespaceID.from("minecraft:oak_stairs_56"), (short) 2010, Block.OAK_STAIRS, "facing=west","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_57 = new BlockState(NamespaceID.from("minecraft:oak_stairs_57"), (short) 2011, Block.OAK_STAIRS, "facing=west","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_58 = new BlockState(NamespaceID.from("minecraft:oak_stairs_58"), (short) 2012, Block.OAK_STAIRS, "facing=west","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_59 = new BlockState(NamespaceID.from("minecraft:oak_stairs_59"), (short) 2013, Block.OAK_STAIRS, "facing=west","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_60 = new BlockState(NamespaceID.from("minecraft:oak_stairs_60"), (short) 2014, Block.OAK_STAIRS, "facing=east","half=top","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_61 = new BlockState(NamespaceID.from("minecraft:oak_stairs_61"), (short) 2015, Block.OAK_STAIRS, "facing=east","half=top","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_62 = new BlockState(NamespaceID.from("minecraft:oak_stairs_62"), (short) 2016, Block.OAK_STAIRS, "facing=east","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_63 = new BlockState(NamespaceID.from("minecraft:oak_stairs_63"), (short) 2017, Block.OAK_STAIRS, "facing=east","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_64 = new BlockState(NamespaceID.from("minecraft:oak_stairs_64"), (short) 2018, Block.OAK_STAIRS, "facing=east","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_65 = new BlockState(NamespaceID.from("minecraft:oak_stairs_65"), (short) 2019, Block.OAK_STAIRS, "facing=east","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_66 = new BlockState(NamespaceID.from("minecraft:oak_stairs_66"), (short) 2020, Block.OAK_STAIRS, "facing=east","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_67 = new BlockState(NamespaceID.from("minecraft:oak_stairs_67"), (short) 2021, Block.OAK_STAIRS, "facing=east","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_68 = new BlockState(NamespaceID.from("minecraft:oak_stairs_68"), (short) 2022, Block.OAK_STAIRS, "facing=east","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_69 = new BlockState(NamespaceID.from("minecraft:oak_stairs_69"), (short) 2023, Block.OAK_STAIRS, "facing=east","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_70 = new BlockState(NamespaceID.from("minecraft:oak_stairs_70"), (short) 2024, Block.OAK_STAIRS, "facing=east","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState OAK_STAIRS_71 = new BlockState(NamespaceID.from("minecraft:oak_stairs_71"), (short) 2025, Block.OAK_STAIRS, "facing=east","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState OAK_STAIRS_72 = new BlockState(NamespaceID.from("minecraft:oak_stairs_72"), (short) 2026, Block.OAK_STAIRS, "facing=east","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_73 = new BlockState(NamespaceID.from("minecraft:oak_stairs_73"), (short) 2027, Block.OAK_STAIRS, "facing=east","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_74 = new BlockState(NamespaceID.from("minecraft:oak_stairs_74"), (short) 2028, Block.OAK_STAIRS, "facing=east","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_75 = new BlockState(NamespaceID.from("minecraft:oak_stairs_75"), (short) 2029, Block.OAK_STAIRS, "facing=east","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState OAK_STAIRS_76 = new BlockState(NamespaceID.from("minecraft:oak_stairs_76"), (short) 2030, Block.OAK_STAIRS, "facing=east","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState OAK_STAIRS_77 = new BlockState(NamespaceID.from("minecraft:oak_stairs_77"), (short) 2031, Block.OAK_STAIRS, "facing=east","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState OAK_STAIRS_78 = new BlockState(NamespaceID.from("minecraft:oak_stairs_78"), (short) 2032, Block.OAK_STAIRS, "facing=east","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState OAK_STAIRS_79 = new BlockState(NamespaceID.from("minecraft:oak_stairs_79"), (short) 2033, Block.OAK_STAIRS, "facing=east","half=bottom","shape=outer_right","waterlogged=false");

  static {
    Registries.registerBlockState(OAK_STAIRS_0);
    Registries.registerBlockState(OAK_STAIRS_1);
    Registries.registerBlockState(OAK_STAIRS_2);
    Registries.registerBlockState(OAK_STAIRS_3);
    Registries.registerBlockState(OAK_STAIRS_4);
    Registries.registerBlockState(OAK_STAIRS_5);
    Registries.registerBlockState(OAK_STAIRS_6);
    Registries.registerBlockState(OAK_STAIRS_7);
    Registries.registerBlockState(OAK_STAIRS_8);
    Registries.registerBlockState(OAK_STAIRS_9);
    Registries.registerBlockState(OAK_STAIRS_10);
    Registries.registerBlockState(OAK_STAIRS_11);
    Registries.registerBlockState(OAK_STAIRS_12);
    Registries.registerBlockState(OAK_STAIRS_13);
    Registries.registerBlockState(OAK_STAIRS_14);
    Registries.registerBlockState(OAK_STAIRS_15);
    Registries.registerBlockState(OAK_STAIRS_16);
    Registries.registerBlockState(OAK_STAIRS_17);
    Registries.registerBlockState(OAK_STAIRS_18);
    Registries.registerBlockState(OAK_STAIRS_19);
    Registries.registerBlockState(OAK_STAIRS_20);
    Registries.registerBlockState(OAK_STAIRS_21);
    Registries.registerBlockState(OAK_STAIRS_22);
    Registries.registerBlockState(OAK_STAIRS_23);
    Registries.registerBlockState(OAK_STAIRS_24);
    Registries.registerBlockState(OAK_STAIRS_25);
    Registries.registerBlockState(OAK_STAIRS_26);
    Registries.registerBlockState(OAK_STAIRS_27);
    Registries.registerBlockState(OAK_STAIRS_28);
    Registries.registerBlockState(OAK_STAIRS_29);
    Registries.registerBlockState(OAK_STAIRS_30);
    Registries.registerBlockState(OAK_STAIRS_31);
    Registries.registerBlockState(OAK_STAIRS_32);
    Registries.registerBlockState(OAK_STAIRS_33);
    Registries.registerBlockState(OAK_STAIRS_34);
    Registries.registerBlockState(OAK_STAIRS_35);
    Registries.registerBlockState(OAK_STAIRS_36);
    Registries.registerBlockState(OAK_STAIRS_37);
    Registries.registerBlockState(OAK_STAIRS_38);
    Registries.registerBlockState(OAK_STAIRS_39);
    Registries.registerBlockState(OAK_STAIRS_40);
    Registries.registerBlockState(OAK_STAIRS_41);
    Registries.registerBlockState(OAK_STAIRS_42);
    Registries.registerBlockState(OAK_STAIRS_43);
    Registries.registerBlockState(OAK_STAIRS_44);
    Registries.registerBlockState(OAK_STAIRS_45);
    Registries.registerBlockState(OAK_STAIRS_46);
    Registries.registerBlockState(OAK_STAIRS_47);
    Registries.registerBlockState(OAK_STAIRS_48);
    Registries.registerBlockState(OAK_STAIRS_49);
    Registries.registerBlockState(OAK_STAIRS_50);
    Registries.registerBlockState(OAK_STAIRS_51);
    Registries.registerBlockState(OAK_STAIRS_52);
    Registries.registerBlockState(OAK_STAIRS_53);
    Registries.registerBlockState(OAK_STAIRS_54);
    Registries.registerBlockState(OAK_STAIRS_55);
    Registries.registerBlockState(OAK_STAIRS_56);
    Registries.registerBlockState(OAK_STAIRS_57);
    Registries.registerBlockState(OAK_STAIRS_58);
    Registries.registerBlockState(OAK_STAIRS_59);
    Registries.registerBlockState(OAK_STAIRS_60);
    Registries.registerBlockState(OAK_STAIRS_61);
    Registries.registerBlockState(OAK_STAIRS_62);
    Registries.registerBlockState(OAK_STAIRS_63);
    Registries.registerBlockState(OAK_STAIRS_64);
    Registries.registerBlockState(OAK_STAIRS_65);
    Registries.registerBlockState(OAK_STAIRS_66);
    Registries.registerBlockState(OAK_STAIRS_67);
    Registries.registerBlockState(OAK_STAIRS_68);
    Registries.registerBlockState(OAK_STAIRS_69);
    Registries.registerBlockState(OAK_STAIRS_70);
    Registries.registerBlockState(OAK_STAIRS_71);
    Registries.registerBlockState(OAK_STAIRS_72);
    Registries.registerBlockState(OAK_STAIRS_73);
    Registries.registerBlockState(OAK_STAIRS_74);
    Registries.registerBlockState(OAK_STAIRS_75);
    Registries.registerBlockState(OAK_STAIRS_76);
    Registries.registerBlockState(OAK_STAIRS_77);
    Registries.registerBlockState(OAK_STAIRS_78);
    Registries.registerBlockState(OAK_STAIRS_79);
  }

  public static void initStates() {
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_0);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_1);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_2);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_3);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_4);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_5);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_6);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_7);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_8);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_9);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_10);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_11);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_12);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_13);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_14);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_15);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_16);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_17);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_18);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_19);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_20);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_21);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_22);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_23);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_24);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_25);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_26);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_27);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_28);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_29);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_30);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_31);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_32);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_33);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_34);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_35);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_36);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_37);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_38);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_39);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_40);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_41);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_42);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_43);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_44);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_45);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_46);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_47);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_48);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_49);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_50);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_51);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_52);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_53);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_54);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_55);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_56);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_57);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_58);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_59);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_60);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_61);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_62);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_63);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_64);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_65);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_66);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_67);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_68);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_69);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_70);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_71);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_72);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_73);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_74);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_75);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_76);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_77);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_78);
    Block.OAK_STAIRS.addBlockState(OAK_STAIRS_79);
  }
}
