package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class OakStairs {
	public static void initStates() {
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1954, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1955, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1956, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1957, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1958, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1959, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1960, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1961, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1962, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1963, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1964, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1965, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1966, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1967, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1968, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1969, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1970, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1971, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1972, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1973, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1974, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1975, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1976, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1977, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1978, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1979, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1980, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1981, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1982, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1983, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1984, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1985, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1986, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1987, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1988, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1989, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1990, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1991, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1992, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1993, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1994, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1995, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1996, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1997, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1998, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 1999, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2000, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2001, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2002, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2003, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2004, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2005, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2006, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2007, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2008, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2009, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2010, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2011, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2012, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2013, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2014, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2015, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2016, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2017, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2018, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2019, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2020, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2021, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2022, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2023, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2024, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2025, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2026, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2027, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2028, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2029, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2030, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2031, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2032, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		OAK_STAIRS.addBlockAlternative(new BlockAlternative((short) 2033, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
