package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class OakWallSign {
  public static final BlockState OAK_WALL_SIGN_0 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_0"), (short) 3735, Block.OAK_WALL_SIGN, "facing=north","waterlogged=true");

  public static final BlockState OAK_WALL_SIGN_1 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_1"), (short) 3736, Block.OAK_WALL_SIGN, "facing=north","waterlogged=false");

  public static final BlockState OAK_WALL_SIGN_2 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_2"), (short) 3737, Block.OAK_WALL_SIGN, "facing=south","waterlogged=true");

  public static final BlockState OAK_WALL_SIGN_3 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_3"), (short) 3738, Block.OAK_WALL_SIGN, "facing=south","waterlogged=false");

  public static final BlockState OAK_WALL_SIGN_4 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_4"), (short) 3739, Block.OAK_WALL_SIGN, "facing=west","waterlogged=true");

  public static final BlockState OAK_WALL_SIGN_5 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_5"), (short) 3740, Block.OAK_WALL_SIGN, "facing=west","waterlogged=false");

  public static final BlockState OAK_WALL_SIGN_6 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_6"), (short) 3741, Block.OAK_WALL_SIGN, "facing=east","waterlogged=true");

  public static final BlockState OAK_WALL_SIGN_7 = new BlockState(NamespaceID.from("minecraft:oak_wall_sign_7"), (short) 3742, Block.OAK_WALL_SIGN, "facing=east","waterlogged=false");

  static {
    Registries.registerBlockState(OAK_WALL_SIGN_0);
    Registries.registerBlockState(OAK_WALL_SIGN_1);
    Registries.registerBlockState(OAK_WALL_SIGN_2);
    Registries.registerBlockState(OAK_WALL_SIGN_3);
    Registries.registerBlockState(OAK_WALL_SIGN_4);
    Registries.registerBlockState(OAK_WALL_SIGN_5);
    Registries.registerBlockState(OAK_WALL_SIGN_6);
    Registries.registerBlockState(OAK_WALL_SIGN_7);
  }

  public static void initStates() {
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_0);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_1);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_2);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_3);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_4);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_5);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_6);
    Block.OAK_WALL_SIGN.addBlockState(OAK_WALL_SIGN_7);
  }
}
