package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class OrangeBed {
  public static final BlockState ORANGE_BED_0 = new BlockState(NamespaceID.from("minecraft:orange_bed_0"), (short) 1065, Block.ORANGE_BED, "facing=north","occupied=true","part=head");

  public static final BlockState ORANGE_BED_1 = new BlockState(NamespaceID.from("minecraft:orange_bed_1"), (short) 1066, Block.ORANGE_BED, "facing=north","occupied=true","part=foot");

  public static final BlockState ORANGE_BED_2 = new BlockState(NamespaceID.from("minecraft:orange_bed_2"), (short) 1067, Block.ORANGE_BED, "facing=north","occupied=false","part=head");

  public static final BlockState ORANGE_BED_3 = new BlockState(NamespaceID.from("minecraft:orange_bed_3"), (short) 1068, Block.ORANGE_BED, "facing=north","occupied=false","part=foot");

  public static final BlockState ORANGE_BED_4 = new BlockState(NamespaceID.from("minecraft:orange_bed_4"), (short) 1069, Block.ORANGE_BED, "facing=south","occupied=true","part=head");

  public static final BlockState ORANGE_BED_5 = new BlockState(NamespaceID.from("minecraft:orange_bed_5"), (short) 1070, Block.ORANGE_BED, "facing=south","occupied=true","part=foot");

  public static final BlockState ORANGE_BED_6 = new BlockState(NamespaceID.from("minecraft:orange_bed_6"), (short) 1071, Block.ORANGE_BED, "facing=south","occupied=false","part=head");

  public static final BlockState ORANGE_BED_7 = new BlockState(NamespaceID.from("minecraft:orange_bed_7"), (short) 1072, Block.ORANGE_BED, "facing=south","occupied=false","part=foot");

  public static final BlockState ORANGE_BED_8 = new BlockState(NamespaceID.from("minecraft:orange_bed_8"), (short) 1073, Block.ORANGE_BED, "facing=west","occupied=true","part=head");

  public static final BlockState ORANGE_BED_9 = new BlockState(NamespaceID.from("minecraft:orange_bed_9"), (short) 1074, Block.ORANGE_BED, "facing=west","occupied=true","part=foot");

  public static final BlockState ORANGE_BED_10 = new BlockState(NamespaceID.from("minecraft:orange_bed_10"), (short) 1075, Block.ORANGE_BED, "facing=west","occupied=false","part=head");

  public static final BlockState ORANGE_BED_11 = new BlockState(NamespaceID.from("minecraft:orange_bed_11"), (short) 1076, Block.ORANGE_BED, "facing=west","occupied=false","part=foot");

  public static final BlockState ORANGE_BED_12 = new BlockState(NamespaceID.from("minecraft:orange_bed_12"), (short) 1077, Block.ORANGE_BED, "facing=east","occupied=true","part=head");

  public static final BlockState ORANGE_BED_13 = new BlockState(NamespaceID.from("minecraft:orange_bed_13"), (short) 1078, Block.ORANGE_BED, "facing=east","occupied=true","part=foot");

  public static final BlockState ORANGE_BED_14 = new BlockState(NamespaceID.from("minecraft:orange_bed_14"), (short) 1079, Block.ORANGE_BED, "facing=east","occupied=false","part=head");

  public static final BlockState ORANGE_BED_15 = new BlockState(NamespaceID.from("minecraft:orange_bed_15"), (short) 1080, Block.ORANGE_BED, "facing=east","occupied=false","part=foot");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_0);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_1);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_2);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_3);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_4);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_5);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_6);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_7);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_8);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_9);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_10);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_11);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_12);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_13);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_14);
    Registry.BLOCK_STATE_REGISTRY.register(ORANGE_BED_15);
  }

  public static void initStates() {
    Block.ORANGE_BED.addBlockState(ORANGE_BED_0);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_1);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_2);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_3);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_4);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_5);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_6);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_7);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_8);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_9);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_10);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_11);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_12);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_13);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_14);
    Block.ORANGE_BED.addBlockState(ORANGE_BED_15);
  }
}
