package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class OrangeWallBanner {
  public static void initStates() {
    Block.ORANGE_WALL_BANNER.addBlockState(new BlockState((short) 8161, Block.ORANGE_WALL_BANNER));
    Block.ORANGE_WALL_BANNER.addBlockState(new BlockState((short) 8162, Block.ORANGE_WALL_BANNER));
    Block.ORANGE_WALL_BANNER.addBlockState(new BlockState((short) 8163, Block.ORANGE_WALL_BANNER));
    Block.ORANGE_WALL_BANNER.addBlockState(new BlockState((short) 8164, Block.ORANGE_WALL_BANNER));
  }
}
