package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class OrangeCarpet {
    public static void initStates() {
        Block.ORANGE_CARPET.addBlockAlternative(new BlockAlternative((short) 7871));
    }
}
