package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class PinkCarpet {
    public static final BlockState PINK_CARPET_0 = new BlockState(NamespaceID.from("minecraft:pink_carpet_0"), (short) 7876, Block.PINK_CARPET);

    static {
        Registry.BLOCK_STATE_REGISTRY.register(PINK_CARPET_0);
    }

    public static void initStates() {
        Block.PINK_CARPET.addBlockState(PINK_CARPET_0);
    }
}
