package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PolishedAndesiteStairs {
	public static void initStates() {
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10633, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10634, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10635, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10636, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10637, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10638, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10639, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10640, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10641, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10642, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10643, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10644, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10645, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10646, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10647, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10648, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10649, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10650, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10651, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10652, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10653, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10654, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10655, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10656, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10657, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10658, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10659, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10660, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10661, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10662, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10663, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10664, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10665, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10666, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10667, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10668, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10669, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10670, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10671, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10672, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10673, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10674, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10675, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10676, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10677, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10678, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10679, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10680, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10681, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10682, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10683, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10684, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10685, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10686, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10687, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10688, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10689, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10690, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10691, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10692, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10693, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10694, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10695, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10696, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10697, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10698, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10699, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10700, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10701, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10702, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10703, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10704, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10705, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10706, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10707, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10708, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10709, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10710, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10711, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_ANDESITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10712, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
