package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PolishedBlackstoneStairs {
	public static void initStates() {
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16673, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16674, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16675, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16676, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16677, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16678, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16679, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16680, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16681, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16682, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16683, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16684, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16685, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16686, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16687, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16688, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16689, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16690, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16691, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16692, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16693, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16694, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16695, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16696, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16697, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16698, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16699, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16700, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16701, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16702, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16703, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16704, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16705, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16706, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16707, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16708, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16709, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16710, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16711, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16712, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16713, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16714, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16715, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16716, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16717, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16718, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16719, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16720, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16721, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16722, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16723, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16724, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16725, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16726, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16727, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16728, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16729, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16730, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16731, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16732, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16733, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16734, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16735, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16736, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16737, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16738, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16739, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16740, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16741, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16742, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16743, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16744, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16745, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16746, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16747, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16748, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16749, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16750, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16751, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 16752, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
