package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PolishedDioriteStairs {
	public static void initStates() {
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9913, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9914, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9915, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9916, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9917, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9918, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9919, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9920, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9921, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9922, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9923, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9924, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9925, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9926, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9927, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9928, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9929, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9930, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9931, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9932, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9933, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9934, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9935, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9936, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9937, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9938, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9939, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9940, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9941, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9942, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9943, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9944, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9945, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9946, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9947, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9948, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9949, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9950, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9951, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9952, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9953, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9954, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9955, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9956, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9957, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9958, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9959, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9960, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9961, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9962, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9963, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9964, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9965, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9966, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9967, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9968, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9969, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9970, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9971, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9972, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9973, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9974, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9975, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9976, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9977, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9978, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9979, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9980, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9981, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9982, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9983, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9984, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9985, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9986, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9987, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9988, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9989, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9990, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9991, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9992, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
