package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PolishedBlackstoneBrickStairs {
	public static void initStates() {
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16268, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16269, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16270, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16271, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16272, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16273, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16274, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16275, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16276, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16277, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16278, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16279, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16280, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16281, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16282, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16283, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16284, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16285, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16286, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16287, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16288, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16289, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16290, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16291, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16292, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16293, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16294, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16295, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16296, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16297, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16298, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16299, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16300, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16301, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16302, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16303, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16304, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16305, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16306, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16307, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16308, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16309, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16310, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16311, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16312, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16313, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16314, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16315, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16316, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16317, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16318, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16319, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16320, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16321, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16322, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16323, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16324, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16325, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16326, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16327, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16328, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16329, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16330, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16331, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16332, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16333, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16334, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16335, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16336, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16337, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16338, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16339, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16340, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16341, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16342, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16343, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16344, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16345, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16346, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_BLACKSTONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 16347, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
