package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PolishedGraniteStairs {
	public static void initStates() {
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9673, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9674, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9675, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9676, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9677, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9678, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9679, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9680, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9681, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9682, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9683, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9684, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9685, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9686, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9687, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9688, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9689, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9690, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9691, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9692, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9693, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9694, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9695, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9696, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9697, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9698, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9699, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9700, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9701, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9702, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9703, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9704, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9705, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9706, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9707, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9708, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9709, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9710, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9711, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9712, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9713, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9714, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9715, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9716, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9717, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9718, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9719, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9720, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9721, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9722, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9723, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9724, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9725, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9726, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9727, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9728, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9729, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9730, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9731, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9732, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9733, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9734, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9735, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9736, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9737, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9738, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9739, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9740, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9741, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9742, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9743, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9744, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9745, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9746, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9747, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9748, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9749, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9750, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9751, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		POLISHED_GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9752, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
