package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Potatoes {
  public static void initStates() {
    Block.POTATOES.addBlockState(new BlockState((short) 6342, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6343, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6344, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6345, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6346, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6347, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6348, Block.POTATOES));
    Block.POTATOES.addBlockState(new BlockState((short) 6349, Block.POTATOES));
  }
}
