package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class PottedOxeyeDaisy {
  public static void initStates() {
    Block.POTTED_OXEYE_DAISY.addBlockState(new BlockState((short) 6326, Block.POTTED_OXEYE_DAISY));
  }
}
