package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PrismarineBrickStairs {
	public static void initStates() {
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7148, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7149, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7150, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7151, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7152, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7153, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7154, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7155, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7156, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7157, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7158, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7159, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7160, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7161, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7162, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7163, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7164, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7165, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7166, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7167, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7168, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7169, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7170, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7171, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7172, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7173, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7174, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7175, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7176, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7177, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7178, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7179, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7180, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7181, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7182, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7183, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7184, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7185, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7186, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7187, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7188, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7189, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7190, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7191, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7192, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7193, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7194, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7195, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7196, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7197, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7198, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7199, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7200, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7201, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7202, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7203, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7204, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7205, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7206, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7207, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7208, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7209, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7210, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7211, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7212, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7213, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7214, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7215, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7216, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7217, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7218, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7219, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7220, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7221, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7222, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7223, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7224, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7225, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7226, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 7227, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
