package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class PrismarineSlab {
    public static final BlockState PRISMARINE_SLAB_0 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_0"), (short) 7848, Block.PRISMARINE_SLAB, "type=top","waterlogged=true");

    public static final BlockState PRISMARINE_SLAB_1 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_1"), (short) 7849, Block.PRISMARINE_SLAB, "type=top","waterlogged=false");

    public static final BlockState PRISMARINE_SLAB_2 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_2"), (short) 7850, Block.PRISMARINE_SLAB, "type=bottom","waterlogged=true");

    public static final BlockState PRISMARINE_SLAB_3 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_3"), (short) 7851, Block.PRISMARINE_SLAB, "type=bottom","waterlogged=false");

    public static final BlockState PRISMARINE_SLAB_4 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_4"), (short) 7852, Block.PRISMARINE_SLAB, "type=double","waterlogged=true");

    public static final BlockState PRISMARINE_SLAB_5 = new BlockState(NamespaceID.from("minecraft:prismarine_slab_5"), (short) 7853, Block.PRISMARINE_SLAB, "type=double","waterlogged=false");

    static {
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_0);
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_1);
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_2);
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_3);
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_4);
        Registry.BLOCK_STATE_REGISTRY.register(PRISMARINE_SLAB_5);
    }

    public static void initStates() {
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_0);
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_1);
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_2);
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_3);
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_4);
        Block.PRISMARINE_SLAB.addBlockState(PRISMARINE_SLAB_5);
    }
}
