package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PrismarineStairs {
	public static void initStates() {
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7608, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7609, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7610, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7611, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7612, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7613, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7614, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7615, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7616, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7617, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7618, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7619, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7620, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7621, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7622, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7623, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7624, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7625, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7626, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7627, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7628, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7629, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7630, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7631, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7632, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7633, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7634, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7635, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7636, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7637, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7638, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7639, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7640, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7641, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7642, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7643, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7644, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7645, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7646, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7647, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7648, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7649, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7650, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7651, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7652, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7653, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7654, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7655, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7656, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7657, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7658, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7659, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7660, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7661, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7662, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7663, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7664, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7665, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7666, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7667, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7668, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7669, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7670, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7671, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7672, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7673, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7674, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7675, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7676, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7677, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7678, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7679, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7680, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7681, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7682, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7683, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7684, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7685, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7686, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7687, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
