package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PurpurStairs {
	public static void initStates() {
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9142, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9143, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9144, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9145, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9146, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9147, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9148, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9149, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9150, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9151, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9152, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9153, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9154, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9155, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9156, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9157, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9158, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9159, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9160, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9161, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9162, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9163, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9164, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9165, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9166, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9167, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9168, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9169, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9170, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9171, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9172, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9173, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9174, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9175, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9176, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9177, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9178, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9179, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9180, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9181, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9182, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9183, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9184, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9185, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9186, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9187, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9188, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9189, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9190, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9191, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9192, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9193, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9194, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9195, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9196, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9197, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9198, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9199, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9200, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9201, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9202, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9203, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9204, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9205, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9206, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9207, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9208, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9209, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9210, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9211, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9212, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9213, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9214, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9215, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9216, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9217, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9218, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9219, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9220, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PURPUR_STAIRS.addBlockAlternative(new BlockAlternative((short) 9221, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
