package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class PurpurPillar {
  public static final BlockState PURPUR_PILLAR_0 = new BlockState(NamespaceID.from("minecraft:purpur_pillar:0"), (short) 9139, Block.PURPUR_PILLAR, "axis=x");

  public static final BlockState PURPUR_PILLAR_1 = new BlockState(NamespaceID.from("minecraft:purpur_pillar:1"), (short) 9140, Block.PURPUR_PILLAR, "axis=y");

  public static final BlockState PURPUR_PILLAR_2 = new BlockState(NamespaceID.from("minecraft:purpur_pillar:2"), (short) 9141, Block.PURPUR_PILLAR, "axis=z");

  static {
    Registries.registerBlockState(PURPUR_PILLAR_0);
    Registries.registerBlockState(PURPUR_PILLAR_1);
    Registries.registerBlockState(PURPUR_PILLAR_2);
  }

  public static void initStates() {
    Block.PURPUR_PILLAR.addBlockState(PURPUR_PILLAR_0);
    Block.PURPUR_PILLAR.addBlockState(PURPUR_PILLAR_1);
    Block.PURPUR_PILLAR.addBlockState(PURPUR_PILLAR_2);
  }
}
