package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class PurpleStainedGlassPane {
  public static void initStates() {
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7187, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7188, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7189, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7190, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7191, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7192, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7193, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7194, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7195, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7196, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7197, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7198, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7199, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7200, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7201, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7202, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7203, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7204, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7205, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7206, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7207, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7208, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7209, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7210, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7211, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7212, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7213, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7214, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7215, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7216, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7217, Block.PURPLE_STAINED_GLASS_PANE));
    Block.PURPLE_STAINED_GLASS_PANE.addBlockState(new BlockState((short) 7218, Block.PURPLE_STAINED_GLASS_PANE));
  }
}
