package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class QuartzStairs {
  public static void initStates() {
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6747, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6748, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6749, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6750, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6751, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6752, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6753, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6754, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6755, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6756, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6757, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6758, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6759, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6760, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6761, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6762, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6763, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6764, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6765, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6766, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6767, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6768, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6769, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6770, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6771, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6772, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6773, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6774, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6775, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6776, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6777, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6778, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6779, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6780, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6781, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6782, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6783, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6784, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6785, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6786, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6787, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6788, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6789, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6790, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6791, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6792, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6793, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6794, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6795, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6796, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6797, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6798, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6799, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6800, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6801, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6802, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6803, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6804, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6805, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6806, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6807, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6808, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6809, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6810, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6811, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6812, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6813, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6814, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6815, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6816, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6817, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6818, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6819, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6820, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6821, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6822, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6823, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6824, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6825, Block.QUARTZ_STAIRS));
    Block.QUARTZ_STAIRS.addBlockState(new BlockState((short) 6826, Block.QUARTZ_STAIRS));
  }
}
