package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class QuartzBlock {
  public static void initStates() {
    Block.QUARTZ_BLOCK.addBlockState(new BlockState((short) 6742, Block.QUARTZ_BLOCK));
  }
}
