package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class QuartzStairs {
	public static void initStates() {
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6747, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6748, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6749, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6750, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6751, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6752, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6753, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6754, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6755, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6756, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6757, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6758, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6759, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6760, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6761, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6762, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6763, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6764, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6765, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6766, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6767, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6768, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6769, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6770, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6771, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6772, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6773, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6774, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6775, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6776, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6777, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6778, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6779, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6780, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6781, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6782, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6783, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6784, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6785, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6786, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6787, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6788, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6789, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6790, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6791, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6792, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6793, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6794, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6795, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6796, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6797, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6798, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6799, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6800, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6801, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6802, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6803, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6804, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6805, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6806, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6807, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6808, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6809, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6810, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6811, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6812, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6813, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6814, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6815, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6816, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6817, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6818, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6819, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6820, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6821, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6822, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6823, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6824, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6825, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6826, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
