package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class RedBanner {
  public static final BlockState RED_BANNER_0 = new BlockState(NamespaceID.from("minecraft:red_banner_0"), (short) 8125, Block.RED_BANNER, "rotation=0");

  public static final BlockState RED_BANNER_1 = new BlockState(NamespaceID.from("minecraft:red_banner_1"), (short) 8126, Block.RED_BANNER, "rotation=1");

  public static final BlockState RED_BANNER_2 = new BlockState(NamespaceID.from("minecraft:red_banner_2"), (short) 8127, Block.RED_BANNER, "rotation=2");

  public static final BlockState RED_BANNER_3 = new BlockState(NamespaceID.from("minecraft:red_banner_3"), (short) 8128, Block.RED_BANNER, "rotation=3");

  public static final BlockState RED_BANNER_4 = new BlockState(NamespaceID.from("minecraft:red_banner_4"), (short) 8129, Block.RED_BANNER, "rotation=4");

  public static final BlockState RED_BANNER_5 = new BlockState(NamespaceID.from("minecraft:red_banner_5"), (short) 8130, Block.RED_BANNER, "rotation=5");

  public static final BlockState RED_BANNER_6 = new BlockState(NamespaceID.from("minecraft:red_banner_6"), (short) 8131, Block.RED_BANNER, "rotation=6");

  public static final BlockState RED_BANNER_7 = new BlockState(NamespaceID.from("minecraft:red_banner_7"), (short) 8132, Block.RED_BANNER, "rotation=7");

  public static final BlockState RED_BANNER_8 = new BlockState(NamespaceID.from("minecraft:red_banner_8"), (short) 8133, Block.RED_BANNER, "rotation=8");

  public static final BlockState RED_BANNER_9 = new BlockState(NamespaceID.from("minecraft:red_banner_9"), (short) 8134, Block.RED_BANNER, "rotation=9");

  public static final BlockState RED_BANNER_10 = new BlockState(NamespaceID.from("minecraft:red_banner_10"), (short) 8135, Block.RED_BANNER, "rotation=10");

  public static final BlockState RED_BANNER_11 = new BlockState(NamespaceID.from("minecraft:red_banner_11"), (short) 8136, Block.RED_BANNER, "rotation=11");

  public static final BlockState RED_BANNER_12 = new BlockState(NamespaceID.from("minecraft:red_banner_12"), (short) 8137, Block.RED_BANNER, "rotation=12");

  public static final BlockState RED_BANNER_13 = new BlockState(NamespaceID.from("minecraft:red_banner_13"), (short) 8138, Block.RED_BANNER, "rotation=13");

  public static final BlockState RED_BANNER_14 = new BlockState(NamespaceID.from("minecraft:red_banner_14"), (short) 8139, Block.RED_BANNER, "rotation=14");

  public static final BlockState RED_BANNER_15 = new BlockState(NamespaceID.from("minecraft:red_banner_15"), (short) 8140, Block.RED_BANNER, "rotation=15");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_0);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_1);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_2);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_3);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_4);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_5);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_6);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_7);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_8);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_9);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_10);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_11);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_12);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_13);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_14);
    Registry.BLOCK_STATE_REGISTRY.register(RED_BANNER_15);
  }

  public static void initStates() {
    Block.RED_BANNER.addBlockState(RED_BANNER_0);
    Block.RED_BANNER.addBlockState(RED_BANNER_1);
    Block.RED_BANNER.addBlockState(RED_BANNER_2);
    Block.RED_BANNER.addBlockState(RED_BANNER_3);
    Block.RED_BANNER.addBlockState(RED_BANNER_4);
    Block.RED_BANNER.addBlockState(RED_BANNER_5);
    Block.RED_BANNER.addBlockState(RED_BANNER_6);
    Block.RED_BANNER.addBlockState(RED_BANNER_7);
    Block.RED_BANNER.addBlockState(RED_BANNER_8);
    Block.RED_BANNER.addBlockState(RED_BANNER_9);
    Block.RED_BANNER.addBlockState(RED_BANNER_10);
    Block.RED_BANNER.addBlockState(RED_BANNER_11);
    Block.RED_BANNER.addBlockState(RED_BANNER_12);
    Block.RED_BANNER.addBlockState(RED_BANNER_13);
    Block.RED_BANNER.addBlockState(RED_BANNER_14);
    Block.RED_BANNER.addBlockState(RED_BANNER_15);
  }
}
