package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockAlternative;

/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class RedConcretePowder {
    public static void initStates() {
        Block.RED_CONCRETE_POWDER.addBlockAlternative(new BlockAlternative((short) 9472));
    }
}
