package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registries;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class RedNetherBrickStairs {
  public static final BlockState RED_NETHER_BRICK_STAIRS_0 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_0"), (short) 10553, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_1 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_1"), (short) 10554, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_2 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_2"), (short) 10555, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_3 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_3"), (short) 10556, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_4 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_4"), (short) 10557, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_5 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_5"), (short) 10558, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_6 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_6"), (short) 10559, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_7 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_7"), (short) 10560, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_8 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_8"), (short) 10561, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_9 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_9"), (short) 10562, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_10 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_10"), (short) 10563, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_11 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_11"), (short) 10564, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_12 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_12"), (short) 10565, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_13 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_13"), (short) 10566, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_14 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_14"), (short) 10567, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_15 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_15"), (short) 10568, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_16 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_16"), (short) 10569, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_17 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_17"), (short) 10570, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_18 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_18"), (short) 10571, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_19 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_19"), (short) 10572, Block.RED_NETHER_BRICK_STAIRS, "facing=north","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_20 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_20"), (short) 10573, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_21 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_21"), (short) 10574, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_22 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_22"), (short) 10575, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_23 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_23"), (short) 10576, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_24 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_24"), (short) 10577, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_25 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_25"), (short) 10578, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_26 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_26"), (short) 10579, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_27 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_27"), (short) 10580, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_28 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_28"), (short) 10581, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_29 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_29"), (short) 10582, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_30 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_30"), (short) 10583, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_31 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_31"), (short) 10584, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_32 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_32"), (short) 10585, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_33 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_33"), (short) 10586, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_34 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_34"), (short) 10587, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_35 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_35"), (short) 10588, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_36 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_36"), (short) 10589, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_37 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_37"), (short) 10590, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_38 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_38"), (short) 10591, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_39 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_39"), (short) 10592, Block.RED_NETHER_BRICK_STAIRS, "facing=south","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_40 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_40"), (short) 10593, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_41 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_41"), (short) 10594, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_42 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_42"), (short) 10595, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_43 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_43"), (short) 10596, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_44 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_44"), (short) 10597, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_45 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_45"), (short) 10598, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_46 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_46"), (short) 10599, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_47 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_47"), (short) 10600, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_48 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_48"), (short) 10601, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_49 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_49"), (short) 10602, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_50 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_50"), (short) 10603, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_51 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_51"), (short) 10604, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_52 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_52"), (short) 10605, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_53 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_53"), (short) 10606, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_54 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_54"), (short) 10607, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_55 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_55"), (short) 10608, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_56 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_56"), (short) 10609, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_57 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_57"), (short) 10610, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_58 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_58"), (short) 10611, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_59 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_59"), (short) 10612, Block.RED_NETHER_BRICK_STAIRS, "facing=west","half=bottom","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_60 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_60"), (short) 10613, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_61 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_61"), (short) 10614, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_62 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_62"), (short) 10615, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_63 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_63"), (short) 10616, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_64 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_64"), (short) 10617, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_65 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_65"), (short) 10618, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_66 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_66"), (short) 10619, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_67 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_67"), (short) 10620, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_68 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_68"), (short) 10621, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_69 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_69"), (short) 10622, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=top","shape=outer_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_70 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_70"), (short) 10623, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=straight","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_71 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_71"), (short) 10624, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=straight","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_72 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_72"), (short) 10625, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=inner_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_73 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_73"), (short) 10626, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=inner_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_74 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_74"), (short) 10627, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=inner_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_75 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_75"), (short) 10628, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=inner_right","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_76 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_76"), (short) 10629, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=outer_left","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_77 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_77"), (short) 10630, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=outer_left","waterlogged=false");

  public static final BlockState RED_NETHER_BRICK_STAIRS_78 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_78"), (short) 10631, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=outer_right","waterlogged=true");

  public static final BlockState RED_NETHER_BRICK_STAIRS_79 = new BlockState(NamespaceID.from("minecraft:red_nether_brick_stairs_79"), (short) 10632, Block.RED_NETHER_BRICK_STAIRS, "facing=east","half=bottom","shape=outer_right","waterlogged=false");

  static {
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_0);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_1);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_2);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_3);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_4);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_5);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_6);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_7);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_8);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_9);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_10);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_11);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_12);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_13);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_14);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_15);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_16);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_17);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_18);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_19);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_20);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_21);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_22);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_23);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_24);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_25);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_26);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_27);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_28);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_29);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_30);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_31);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_32);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_33);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_34);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_35);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_36);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_37);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_38);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_39);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_40);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_41);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_42);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_43);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_44);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_45);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_46);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_47);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_48);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_49);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_50);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_51);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_52);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_53);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_54);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_55);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_56);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_57);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_58);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_59);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_60);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_61);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_62);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_63);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_64);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_65);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_66);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_67);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_68);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_69);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_70);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_71);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_72);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_73);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_74);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_75);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_76);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_77);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_78);
    Registries.registerBlockState(RED_NETHER_BRICK_STAIRS_79);
  }

  public static void initStates() {
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_0);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_1);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_2);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_3);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_4);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_5);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_6);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_7);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_8);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_9);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_10);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_11);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_12);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_13);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_14);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_15);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_16);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_17);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_18);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_19);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_20);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_21);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_22);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_23);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_24);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_25);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_26);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_27);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_28);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_29);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_30);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_31);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_32);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_33);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_34);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_35);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_36);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_37);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_38);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_39);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_40);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_41);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_42);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_43);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_44);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_45);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_46);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_47);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_48);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_49);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_50);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_51);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_52);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_53);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_54);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_55);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_56);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_57);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_58);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_59);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_60);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_61);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_62);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_63);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_64);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_65);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_66);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_67);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_68);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_69);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_70);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_71);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_72);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_73);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_74);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_75);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_76);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_77);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_78);
    Block.RED_NETHER_BRICK_STAIRS.addBlockState(RED_NETHER_BRICK_STAIRS_79);
  }
}
