package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class RedNetherBrickStairs {
	public static void initStates() {
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10553, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10554, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10555, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10556, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10557, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10558, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10559, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10560, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10561, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10562, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10563, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10564, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10565, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10566, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10567, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10568, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10569, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10570, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10571, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10572, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10573, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10574, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10575, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10576, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10577, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10578, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10579, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10580, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10581, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10582, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10583, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10584, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10585, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10586, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10587, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10588, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10589, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10590, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10591, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10592, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10593, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10594, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10595, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10596, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10597, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10598, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10599, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10600, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10601, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10602, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10603, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10604, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10605, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10606, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10607, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10608, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10609, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10610, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10611, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10612, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10613, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10614, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10615, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10616, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10617, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10618, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10619, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10620, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10621, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10622, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10623, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10624, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10625, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10626, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10627, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10628, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10629, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10630, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10631, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10632, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
