package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class RedNetherBrickStairs {
	public static void initStates() {
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10013, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10014, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10015, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10016, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10017, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10018, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10019, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10020, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10021, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10022, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10023, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10024, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10025, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10026, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10027, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10028, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10029, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10030, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10031, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10032, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10033, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10034, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10035, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10036, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10037, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10038, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10039, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10040, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10041, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10042, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10043, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10044, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10045, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10046, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10047, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10048, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10049, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10050, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10051, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10052, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10053, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10054, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10055, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10056, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10057, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10058, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10059, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10060, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10061, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10062, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10063, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10064, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10065, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10066, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10067, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10068, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10069, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10070, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10071, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10072, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10073, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10074, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10075, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10076, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10077, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10078, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10079, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10080, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10081, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10082, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10083, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10084, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10085, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10086, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10087, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10088, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10089, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10090, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10091, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 10092, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
