package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class RedSandstoneStairs {
	public static void initStates() {
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8224, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8225, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8226, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8227, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8228, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8229, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8230, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8231, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8232, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8233, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8234, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8235, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8236, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8237, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8238, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8239, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8240, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8241, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8242, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8243, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8244, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8245, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8246, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8247, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8248, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8249, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8250, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8251, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8252, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8253, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8254, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8255, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8256, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8257, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8258, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8259, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8260, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8261, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8262, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8263, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8264, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8265, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8266, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8267, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8268, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8269, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8270, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8271, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8272, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8273, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8274, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8275, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8276, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8277, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8278, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8279, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8280, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8281, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8282, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8283, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8284, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8285, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8286, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8287, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8288, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8289, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8290, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8291, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8292, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8293, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8294, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8295, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8296, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8297, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8298, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8299, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8300, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8301, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8302, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 8303, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
