package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class RedTerracotta {
    public static final BlockState RED_TERRACOTTA_0 = new BlockState(NamespaceID.from("minecraft:red_terracotta_0"), (short) 6865, Block.RED_TERRACOTTA);

    static {
        Registry.BLOCK_STATE_REGISTRY.register(RED_TERRACOTTA_0);
    }

    public static void initStates() {
        Block.RED_TERRACOTTA.addBlockState(RED_TERRACOTTA_0);
    }
}
