package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class RedTulip {
  public static void initStates() {
    Block.RED_TULIP.addBlockState(new BlockState((short) 1417, Block.RED_TULIP));
  }
}
