package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class RepeatingCommandBlock {
  public static void initStates() {
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9229, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9230, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9231, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9232, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9233, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9234, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9235, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9236, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9237, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9238, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9239, Block.REPEATING_COMMAND_BLOCK));
    Block.REPEATING_COMMAND_BLOCK.addBlockState(new BlockState((short) 9240, Block.REPEATING_COMMAND_BLOCK));
  }
}
