package net.minestom.server.instance.block.states;

import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;


/**
 * AUTOGENERATED by BlockGenerator
 */
@Deprecated(
        since = "forever",
        forRemoval = false
)
public final class Sand {
    public static final BlockState SAND_0 = new BlockState(NamespaceID.from("minecraft:sand_0"), (short) 66, Block.SAND);

    static {
        Registry.BLOCK_STATE_REGISTRY.register(SAND_0);
    }

    public static void initStates() {
        Block.SAND.addBlockState(SAND_0);
    }
}
