package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SandstoneStairs {
	public static void initStates() {
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5174, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5175, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5176, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5177, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5178, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5179, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5180, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5181, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5182, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5183, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5184, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5185, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5186, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5187, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5188, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5189, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5190, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5191, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5192, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5193, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5194, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5195, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5196, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5197, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5198, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5199, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5200, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5201, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5202, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5203, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5204, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5205, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5206, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5207, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5208, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5209, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5210, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5211, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5212, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5213, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5214, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5215, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5216, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5217, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5218, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5219, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5220, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5221, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5222, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5223, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5224, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5225, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5226, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5227, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5228, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5229, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5230, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5231, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5232, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5233, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5234, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5235, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5236, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5237, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5238, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5239, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5240, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5241, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5242, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5243, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5244, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5245, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5246, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5247, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5248, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5249, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5250, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5251, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5252, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5253, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
