package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SmoothQuartzStairs {
	public static void initStates() {
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10313, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10314, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10315, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10316, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10317, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10318, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10319, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10320, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10321, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10322, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10323, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10324, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10325, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10326, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10327, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10328, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10329, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10330, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10331, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10332, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10333, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10334, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10335, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10336, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10337, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10338, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10339, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10340, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10341, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10342, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10343, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10344, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10345, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10346, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10347, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10348, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10349, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10350, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10351, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10352, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10353, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10354, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10355, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10356, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10357, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10358, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10359, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10360, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10361, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10362, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10363, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10364, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10365, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10366, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10367, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10368, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10369, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10370, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10371, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10372, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10373, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10374, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10375, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10376, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10377, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10378, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10379, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10380, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10381, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10382, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10383, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10384, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10385, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10386, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10387, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10388, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10389, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10390, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10391, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 10392, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
