package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SmoothRedSandstoneStairs {
	public static void initStates() {
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9753, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9754, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9755, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9756, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9757, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9758, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9759, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9760, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9761, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9762, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9763, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9764, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9765, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9766, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9767, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9768, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9769, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9770, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9771, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9772, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9773, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9774, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9775, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9776, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9777, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9778, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9779, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9780, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9781, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9782, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9783, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9784, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9785, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9786, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9787, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9788, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9789, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9790, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9791, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9792, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9793, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9794, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9795, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9796, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9797, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9798, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9799, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9800, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9801, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9802, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9803, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9804, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9805, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9806, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9807, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9808, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9809, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9810, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9811, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9812, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9813, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9814, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9815, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9816, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9817, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9818, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9819, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9820, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9821, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9822, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9823, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9824, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9825, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9826, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9827, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9828, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9829, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9830, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9831, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SMOOTH_RED_SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9832, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
