package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class SpruceSlab {
  public static void initStates() {
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8310, Block.SPRUCE_SLAB));
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8311, Block.SPRUCE_SLAB));
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8312, Block.SPRUCE_SLAB));
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8313, Block.SPRUCE_SLAB));
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8314, Block.SPRUCE_SLAB));
    Block.SPRUCE_SLAB.addBlockState(new BlockState((short) 8315, Block.SPRUCE_SLAB));
  }
}
