package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SpruceStairs {
	public static void initStates() {
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5388, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5389, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5390, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5391, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5392, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5393, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5394, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5395, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5396, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5397, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5398, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5399, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5400, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5401, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5402, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5403, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5404, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5405, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5406, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5407, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5408, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5409, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5410, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5411, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5412, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5413, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5414, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5415, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5416, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5417, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5418, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5419, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5420, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5421, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5422, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5423, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5424, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5425, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5426, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5427, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5428, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5429, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5430, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5431, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5432, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5433, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5434, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5435, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5436, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5437, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5438, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5439, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5440, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5441, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5442, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5443, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5444, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5445, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5446, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5447, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5448, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5449, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5450, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5451, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5452, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5453, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5454, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5455, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5456, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5457, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5458, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5459, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5460, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5461, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5462, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5463, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5464, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5465, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5466, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5467, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
