package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class SpruceWallSign {
  public static void initStates() {
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3743, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3744, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3745, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3746, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3747, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3748, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3749, Block.SPRUCE_WALL_SIGN));
    Block.SPRUCE_WALL_SIGN.addBlockState(new BlockState((short) 3750, Block.SPRUCE_WALL_SIGN));
  }
}
