package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class SpruceSign {
  public static void initStates() {
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3413, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3414, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3415, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3416, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3417, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3418, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3419, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3420, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3421, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3422, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3423, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3424, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3425, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3426, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3427, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3428, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3429, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3430, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3431, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3432, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3433, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3434, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3435, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3436, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3437, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3438, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3439, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3440, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3441, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3442, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3443, Block.SPRUCE_SIGN));
    Block.SPRUCE_SIGN.addBlockState(new BlockState((short) 3444, Block.SPRUCE_SIGN));
  }
}
