package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class SpruceLog {
  public static final BlockState SPRUCE_LOG_0 = new BlockState(NamespaceID.from("minecraft:spruce_log_0"), (short) 76, Block.SPRUCE_LOG, "axis=x");

  public static final BlockState SPRUCE_LOG_1 = new BlockState(NamespaceID.from("minecraft:spruce_log_1"), (short) 77, Block.SPRUCE_LOG, "axis=y");

  public static final BlockState SPRUCE_LOG_2 = new BlockState(NamespaceID.from("minecraft:spruce_log_2"), (short) 78, Block.SPRUCE_LOG, "axis=z");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(SPRUCE_LOG_0);
    Registry.BLOCK_STATE_REGISTRY.register(SPRUCE_LOG_1);
    Registry.BLOCK_STATE_REGISTRY.register(SPRUCE_LOG_2);
  }

  public static void initStates() {
    Block.SPRUCE_LOG.addBlockState(SPRUCE_LOG_0);
    Block.SPRUCE_LOG.addBlockState(SPRUCE_LOG_1);
    Block.SPRUCE_LOG.addBlockState(SPRUCE_LOG_2);
  }
}
