package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class SpruceTrapdoor {
  public static void initStates() {
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4175, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4176, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4177, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4178, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4179, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4180, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4181, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4182, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4183, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4184, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4185, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4186, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4187, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4188, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4189, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4190, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4191, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4192, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4193, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4194, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4195, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4196, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4197, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4198, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4199, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4200, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4201, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4202, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4203, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4204, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4205, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4206, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4207, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4208, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4209, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4210, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4211, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4212, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4213, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4214, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4215, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4216, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4217, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4218, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4219, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4220, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4221, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4222, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4223, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4224, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4225, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4226, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4227, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4228, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4229, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4230, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4231, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4232, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4233, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4234, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4235, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4236, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4237, Block.SPRUCE_TRAPDOOR));
    Block.SPRUCE_TRAPDOOR.addBlockState(new BlockState((short) 4238, Block.SPRUCE_TRAPDOOR));
  }
}
