package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SpruceStairs {
	public static void initStates() {
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5408, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5409, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5410, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5411, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5412, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5413, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5414, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5415, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5416, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5417, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5418, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5419, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5420, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5421, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5422, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5423, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5424, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5425, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5426, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5427, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5428, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5429, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5430, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5431, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5432, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5433, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5434, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5435, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5436, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5437, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5438, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5439, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5440, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5441, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5442, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5443, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5444, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5445, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5446, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5447, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5448, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5449, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5450, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5451, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5452, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5453, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5454, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5455, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5456, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5457, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5458, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5459, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5460, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5461, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5462, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5463, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5464, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5465, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5466, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5467, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5468, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5469, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5470, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5471, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5472, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5473, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5474, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5475, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5476, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5477, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5478, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5479, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5480, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5481, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5482, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5483, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5484, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5485, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5486, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SPRUCE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5487, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
