package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class StoneBrickStairs {
	public static void initStates() {
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4936, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4937, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4938, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4939, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4940, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4941, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4942, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4943, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4944, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4945, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4946, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4947, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4948, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4949, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4950, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4951, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4952, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4953, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4954, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4955, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4956, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4957, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4958, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4959, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4960, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4961, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4962, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4963, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4964, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4965, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4966, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4967, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4968, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4969, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4970, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4971, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4972, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4973, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4974, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4975, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4976, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4977, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4978, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4979, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4980, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4981, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4982, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4983, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4984, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4985, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4986, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4987, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4988, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4989, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4990, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4991, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4992, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4993, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4994, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4995, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4996, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4997, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4998, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4999, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5000, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5001, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5002, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5003, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5004, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5005, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5006, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5007, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5008, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5009, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5010, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5011, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5012, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5013, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5014, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5015, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
