package net.minestom.server.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.server.instance.block.Block.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class StoneStairs {
	public static void initStates() {
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10153, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10154, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10155, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10156, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10157, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10158, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10159, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10160, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10161, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10162, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10163, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10164, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10165, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10166, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10167, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10168, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10169, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10170, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10171, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10172, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10173, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10174, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10175, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10176, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10177, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10178, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10179, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10180, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10181, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10182, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10183, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10184, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10185, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10186, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10187, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10188, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10189, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10190, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10191, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10192, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10193, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10194, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10195, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10196, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10197, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10198, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10199, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10200, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10201, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10202, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10203, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10204, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10205, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10206, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10207, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10208, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10209, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10210, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10211, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10212, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10213, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10214, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10215, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10216, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10217, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10218, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10219, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10220, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10221, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10222, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10223, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10224, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10225, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10226, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10227, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10228, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10229, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10230, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10231, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10232, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
