package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class StrippedCrimsonHyphae {
  public static void initStates() {
    Block.STRIPPED_CRIMSON_HYPHAE.addBlockState(new BlockState((short) 14992, Block.STRIPPED_CRIMSON_HYPHAE));
    Block.STRIPPED_CRIMSON_HYPHAE.addBlockState(new BlockState((short) 14993, Block.STRIPPED_CRIMSON_HYPHAE));
    Block.STRIPPED_CRIMSON_HYPHAE.addBlockState(new BlockState((short) 14994, Block.STRIPPED_CRIMSON_HYPHAE));
  }
}
