package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class StrippedOakLog {
  public static void initStates() {
    Block.STRIPPED_OAK_LOG.addBlockState(new BlockState((short) 106, Block.STRIPPED_OAK_LOG));
    Block.STRIPPED_OAK_LOG.addBlockState(new BlockState((short) 107, Block.STRIPPED_OAK_LOG));
    Block.STRIPPED_OAK_LOG.addBlockState(new BlockState((short) 108, Block.STRIPPED_OAK_LOG));
  }
}
