package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.registry.Registry;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class WarpedStem {
  public static final BlockState WARPED_STEM_0 = new BlockState(NamespaceID.from("minecraft:warped_stem_0"), (short) 14966, Block.WARPED_STEM, "axis=x");

  public static final BlockState WARPED_STEM_1 = new BlockState(NamespaceID.from("minecraft:warped_stem_1"), (short) 14967, Block.WARPED_STEM, "axis=y");

  public static final BlockState WARPED_STEM_2 = new BlockState(NamespaceID.from("minecraft:warped_stem_2"), (short) 14968, Block.WARPED_STEM, "axis=z");

  static {
    Registry.BLOCK_STATE_REGISTRY.register(WARPED_STEM_0);
    Registry.BLOCK_STATE_REGISTRY.register(WARPED_STEM_1);
    Registry.BLOCK_STATE_REGISTRY.register(WARPED_STEM_2);
  }

  public static void initStates() {
    Block.WARPED_STEM.addBlockState(WARPED_STEM_0);
    Block.WARPED_STEM.addBlockState(WARPED_STEM_1);
    Block.WARPED_STEM.addBlockState(WARPED_STEM_2);
  }
}
