package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;
import net.minestom.server.utils.NamespaceID;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class Wheat {
  public static final BlockState WHEAT_0 = new BlockState(NamespaceID.from("minecraft:wheat:0"), (short) 3357, Block.WHEAT);

  public static final BlockState WHEAT_1 = new BlockState(NamespaceID.from("minecraft:wheat:1"), (short) 3358, Block.WHEAT);

  public static final BlockState WHEAT_2 = new BlockState(NamespaceID.from("minecraft:wheat:2"), (short) 3359, Block.WHEAT);

  public static final BlockState WHEAT_3 = new BlockState(NamespaceID.from("minecraft:wheat:3"), (short) 3360, Block.WHEAT);

  public static final BlockState WHEAT_4 = new BlockState(NamespaceID.from("minecraft:wheat:4"), (short) 3361, Block.WHEAT);

  public static final BlockState WHEAT_5 = new BlockState(NamespaceID.from("minecraft:wheat:5"), (short) 3362, Block.WHEAT);

  public static final BlockState WHEAT_6 = new BlockState(NamespaceID.from("minecraft:wheat:6"), (short) 3363, Block.WHEAT);

  public static final BlockState WHEAT_7 = new BlockState(NamespaceID.from("minecraft:wheat:7"), (short) 3364, Block.WHEAT);

  public static void initStates() {
    Block.WHEAT.addBlockState(WHEAT_0);
    Block.WHEAT.addBlockState(WHEAT_1);
    Block.WHEAT.addBlockState(WHEAT_2);
    Block.WHEAT.addBlockState(WHEAT_3);
    Block.WHEAT.addBlockState(WHEAT_4);
    Block.WHEAT.addBlockState(WHEAT_5);
    Block.WHEAT.addBlockState(WHEAT_6);
    Block.WHEAT.addBlockState(WHEAT_7);
  }
}
