package net.minestom.server.instance.block.states;

import java.lang.Deprecated;
import net.minestom.server.instance.block.Block;
import net.minestom.server.instance.block.BlockState;

/**
 * AUTOGENERATED
 */
@Deprecated(
    since = "forever",
    forRemoval = false
)
public final class WitherSkeletonSkull {
  public static void initStates() {
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6514, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6515, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6516, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6517, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6518, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6519, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6520, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6521, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6522, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6523, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6524, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6525, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6526, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6527, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6528, Block.WITHER_SKELETON_SKULL));
    Block.WITHER_SKELETON_SKULL.addBlockState(new BlockState((short) 6529, Block.WITHER_SKELETON_SKULL));
  }
}
