name: Report a bug
description: You found a bug? Let us know!
title: "[Bug]: "
labels: [ "bug", "needs triage" ]
projects: ["minestom/6"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug to Minestom!
        Please fill out the information below to help us understand the issue.
  - type: markdown
    attributes:
      value: |
        Before filling in the form fields, please consider the following:
        - Ensure that you are using the latest version of Minestom.
        - Search for existing issues in the [issue tracker](https://github.com/Minestom/Minestom/issues)
  - type: textarea
    attributes:
      label: Affected Version
      description: |
        The unique version of the used dependency.
        It can be found out via the Git class or in the dependency.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        If you have a screenshot of the bug, please attach it below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Tell us exactly how to reproduce the bug you are experiencing
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a reproducible sample to show us the bug in action and attach it below between the lines with the backticks.
        This helps us to verify that the bug is valid and prevents us from having to ask you for a sample later.
        
        Without this we will be unlikely to be able to progress on the issue, so
        we'll regretfully have to close it.

        **Note**: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        ```java
        [Paste your code here]
        ```
    validations:
      required: false