package net.minestom.server;

/**
 * AUTOGENERATED by ConstantsGenerator
 */
interface MinecraftConstants {
    String VERSION_NAME = "1.21.2-pre1";

    int PROTOCOL_VERSION = 1073742037;

    int DATA_VERSION = 4073;

    int RESOURCE_PACK_VERSION = 41;

    int DATA_PACK_VERSION = 57;
}
