package net.minestom.server;

/**
 * AUTOGENERATED by ConstantsGenerator
 */
interface MinecraftConstants {
    String VERSION_NAME = "1.21.7";

    int PROTOCOL_VERSION = 772;

    int DATA_VERSION = 4438;

    int RESOURCE_PACK_VERSION = 64;

    int DATA_PACK_VERSION = 81;
}
