description = "The core of the Minestom server"

sourceSets {
    main {
        java {
            srcDir("src/main/java")
            srcDir("src/autogenerated/java")
            srcDir("src/generators/java")
        }
    }
}

dependencies {
    // netty - client/server communications
    val nettyVersion = "4.1.63.Final"
    api("io.netty", "netty-handler", nettyVersion)
    api("io.netty", "netty-codec", nettyVersion)
    api("io.netty", "netty-transport-native-epoll", nettyVersion, "","linux-x86_64")
    api("io.netty", "netty-transport-native-kqueue", nettyVersion, "", "osx-x86_64")
    api("io.netty.incubator", "netty-incubator-transport-native-io_uring", "0.0.5.Final", "", "linux-x86_64")

    // commons-text - util methods for text
    compileOnly("org.apache.commons", "commons-text", "1.9")

    // fastutil - faster type-specific collections
    api("it.unimi.dsi", "fastutil", "8.5.4")

    // gson - writing/reading json
    api("com.google.code.gson", "gson", "2.8.6")

    // jnoise - terrain generation
    api("com.github.Articdive", "Jnoise", "2.1.0")

    // rocksdb - file storage
    api("org.rocksdb", "rocksdbjni", "6.16.4")

    // log4j - logging framework
    val log4jVersion = "2.14.0"
    api("org.apache.logging.log4j", "log4j-core", log4jVersion)
    api("org.apache.logging.log4j", "log4j-slf4j-impl", log4jVersion)

    // jline - console input and formatting
    implementation("org.jline", "jline", "3.20.0")

    // jansi - ansi colorization on windows terminals
    implementation("org.fusesource.jansi", "jansi", "2.3.2")

    // guava - google common utilities
    api("com.google.guava", "guava", "30.1-jre")

    // authlib - online mode authentication
    api("com.mojang", "authlib", "1.5.21")

    // asm - bytecode generation and analysis
    val asmVersion = "9.0"
    api("org.ow2.asm", "asm", asmVersion)
    api("org.ow2.asm", "asm-tree", asmVersion)
    api("org.ow2.asm", "asm-analysis", asmVersion)
    api("org.ow2.asm", "asm-util", asmVersion)
    api("org.ow2.asm", "asm-commons", asmVersion)

    // mixin - allows extensions to modify internal code
    api("org.spongepowered", "mixin", "0.8.1")

    // velocity native - networking compression
    implementation("com.velocitypowered", "velocity-native", "1.1.0-SNAPSHOT")

    // hydrazine - path finding
    api("com.github.MadMartian", "hydrazine-path-finding", "1.6.0")

    // kotlin
    val kotlinVersion = "1.5.0"
    api("org.jetbrains.kotlin", "kotlin-stdlib-jdk8", kotlinVersion)
    api("org.jetbrains.kotlin", "kotlin-reflect", kotlinVersion)

    // hephaistos - nbt reading/writing
    val hephaistosVersion = "v1.1.8"
    api("com.github.jglrxavpok", "Hephaistos", hephaistosVersion)
    api("com.github.jglrxavpok", "Hephaistos", hephaistosVersion, "", "gson")
    api("com.github.jglrxavpok", "Hephaistos", hephaistosVersion) {
        capabilities {
            requireCapabilities("org.jglrxavpok.nbt:Hephaistos-gson")
        }
    }

    // dependency getter - download extension dependencies
    api("com.github.Minestom", "DependencyGetter", "v1.0.1")

    // adventure - user interface api
    val adventureVersion = "4.7.0"
    api("net.kyori", "adventure-api", adventureVersion)
    api("net.kyori", "adventure-text-serializer-gson", adventureVersion)
    api("net.kyori", "adventure-text-serializer-legacy", adventureVersion)
    api("net.kyori", "adventure-text-serializer-plain", adventureVersion)

    // javapoet - generate java code for data generator
    implementation("com.squareup", "javapoet", "1.13.0")
}