package net.minestom.server.entity.metadata.animal;

import net.minestom.server.registry.RegistryKey;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface FrogVariants {
    RegistryKey<FrogVariant> WARM = RegistryKey.unsafeOf("minecraft:warm");

    RegistryKey<FrogVariant> COLD = RegistryKey.unsafeOf("minecraft:cold");

    RegistryKey<FrogVariant> TEMPERATE = RegistryKey.unsafeOf("minecraft:temperate");
}
