package net.minestom.server.tags;

import net.minestom.server.MinecraftServer;
import net.minestom.server.instance.block.Block;
import org.jetbrains.annotations.NotNull;

// TODO: This could probably be auto-generated
public final class BlockTags {

    public static final @NotNull Tag<@NotNull Block> ACACIA_LOGS = get("acacia_logs");
    public static final @NotNull Tag<@NotNull Block> ANVILS = get("anvil");
    public static final @NotNull Tag<@NotNull Block> BAMBOO_PLANTABLE_ON = get("bamboo_plantable_on");
    public static final @NotNull Tag<@NotNull Block> BANNERS = get("banners");
    public static final @NotNull Tag<@NotNull Block> BASE_STONE_NETHER = get("base_stone_nether");
    public static final @NotNull Tag<@NotNull Block> BASE_STONE_OVERWORLD = get("base_stone_overworld");
    public static final @NotNull Tag<@NotNull Block> BEACON_BASE_BLOCKS = get("beacon_base_blocks");
    public static final @NotNull Tag<@NotNull Block> BEDS = get("beds");
    public static final @NotNull Tag<@NotNull Block> BEEHIVES = get("beehives");
    public static final @NotNull Tag<@NotNull Block> BEE_GROWABLES = get("bee_growables");
    public static final @NotNull Tag<@NotNull Block> BIRCH_LOGS = get("birch_logs");
    public static final @NotNull Tag<@NotNull Block> BUTTONS = get("buttons");
    public static final @NotNull Tag<@NotNull Block> CAMPFIRES = get("campfires");
    public static final @NotNull Tag<@NotNull Block> CANDLE_CAKES = get("candle_cakes");
    public static final @NotNull Tag<@NotNull Block> CANDLES = get("candles");
    public static final @NotNull Tag<@NotNull Block> CARPETS = get("carpets");
    public static final @NotNull Tag<@NotNull Block> CAULDRONS = get("cauldrons");
    public static final @NotNull Tag<@NotNull Block> CAVE_VINES = get("cave_vines");
    public static final @NotNull Tag<@NotNull Block> CLIMBABLE = get("climbable");
    public static final @NotNull Tag<@NotNull Block> COAL_ORES = get("coal_ores");
    public static final @NotNull Tag<@NotNull Block> COPPER_ORES = get("copper_ores");
    public static final @NotNull Tag<@NotNull Block> CORALS = get("corals");
    public static final @NotNull Tag<@NotNull Block> CORAL_BLOCKS = get("coral_blocks");
    public static final @NotNull Tag<@NotNull Block> CORAL_PLANTS = get("coral_plants");
    public static final @NotNull Tag<@NotNull Block> CRIMSON_STEMS = get("crimson_stems");
    public static final @NotNull Tag<@NotNull Block> CROPS = get("crops");
    public static final @NotNull Tag<@NotNull Block> CRYSTAL_SOUND_BLOCKS = get("crystal_sound_blocks");
    public static final @NotNull Tag<@NotNull Block> DARK_OAK_LOGS = get("dark_oak_logs");
    public static final @NotNull Tag<@NotNull Block> DEEPSLATE_ORE_REPLACEABLES = get("deepslate_ore_replaceables");
    public static final @NotNull Tag<@NotNull Block> DIAMOND_ORES = get("diamond_ores");
    public static final @NotNull Tag<@NotNull Block> DIRT = get("dirt");
    public static final @NotNull Tag<@NotNull Block> DOORS = get("doors");
    public static final @NotNull Tag<@NotNull Block> DRAGON_IMMUNE = get("dragon_immune");
    public static final @NotNull Tag<@NotNull Block> DRIPSTONE_REPLACEABLE_BLOCKS = get("dripstone_replaceable_blocks");
    public static final @NotNull Tag<@NotNull Block> EMERALD_ORES = get("emerald_ores");
    public static final @NotNull Tag<@NotNull Block> ENDERMAN_HOLDABLE = get("enderman_holdable");
    public static final @NotNull Tag<@NotNull Block> FEATURES_CANNOT_REPLACE = get("features_cannot_replace");
    public static final @NotNull Tag<@NotNull Block> FENCE_GATES = get("fence_gates");
    public static final @NotNull Tag<@NotNull Block> FENCES = get("fences");
    public static final @NotNull Tag<@NotNull Block> FIRE = get("fire");
    public static final @NotNull Tag<@NotNull Block> FLOWER_POTS = get("flower_pots");
    public static final @NotNull Tag<@NotNull Block> FLOWERS = get("flowers");
    public static final @NotNull Tag<@NotNull Block> GEODE_INVALID_BLOCKS = get("geode_invalid_blocks");
    public static final @NotNull Tag<@NotNull Block> GOLD_ORES = get("gold_ores");
    public static final @NotNull Tag<@NotNull Block> GUARDED_BY_PIGLINS = get("guarded_by_piglins");
    public static final @NotNull Tag<@NotNull Block> HOGLIN_REPELLENTS = get("hoglin_repellents");
    public static final @NotNull Tag<@NotNull Block> ICE = get("ice");
    public static final @NotNull Tag<@NotNull Block> IMPERMEABLE = get("impermeable");
    public static final @NotNull Tag<@NotNull Block> INFINIBURN_END = get("infiniburn_end");
    public static final @NotNull Tag<@NotNull Block> INFINIBURN_NETHER = get("infiniburn_nether");
    public static final @NotNull Tag<@NotNull Block> INFINIBURN_OVERWORLD = get("infiniburn_overworld");
    public static final @NotNull Tag<@NotNull Block> INSIDE_STEP_SOUND_BLOCKS = get("inside_step_sound_blocks");
    public static final @NotNull Tag<@NotNull Block> IRON_ORES = get("iron_ores");
    public static final @NotNull Tag<@NotNull Block> JUNGLE_LOGS = get("jungle_logs");
    public static final @NotNull Tag<@NotNull Block> LAPIS_ORES = get("lapis_ores");
    public static final @NotNull Tag<@NotNull Block> LAVA_POOL_STONE_REPLACEABLES = get("lava_pool_stone_replaceables");
    public static final @NotNull Tag<@NotNull Block> LEAVES = get("leaves");
    public static final @NotNull Tag<@NotNull Block> LOGS = get("logs");
    public static final @NotNull Tag<@NotNull Block> LOGS_THAT_BURN = get("logs_that_burn");
    public static final @NotNull Tag<@NotNull Block> LUSH_GROUND_REPLACEABLE = get("lush_ground_replaceable");
    public static final @NotNull Tag<@NotNull Block> MINEABLE_AXE = get("mineable/axe");
    public static final @NotNull Tag<@NotNull Block> MINEABLE_HOE = get("mineable/hoe");
    public static final @NotNull Tag<@NotNull Block> MINEABLE_PICKAXE = get("mineable/pickaxe");
    public static final @NotNull Tag<@NotNull Block> MINEABLE_SHOVEL = get("mineable/shovel");
    public static final @NotNull Tag<@NotNull Block> MOSS_REPLACEABLE = get("moss_replaceable");
    public static final @NotNull Tag<@NotNull Block> MUSHROOM_GROW_BLOCK = get("mushroom_grow_block");
    public static final @NotNull Tag<@NotNull Block> NEEDS_DIAMOND_TOOL = get("needs_diamond_tool");
    public static final @NotNull Tag<@NotNull Block> NEEDS_IRON_TOOL = get("needs_iron_tool");
    public static final @NotNull Tag<@NotNull Block> NEEDS_STONE_TOOL = get("needs_stone_tool");
    public static final @NotNull Tag<@NotNull Block> NON_FLAMMABLE_WOOD = get("non_flammable_wood");
    public static final @NotNull Tag<@NotNull Block> NYLIUM = get("nylium");
    public static final @NotNull Tag<@NotNull Block> OAK_LOGS = get("oak_logs");
    public static final @NotNull Tag<@NotNull Block> OCCLUDES_VIBRATION_SIGNALS = get("occludes_vibration_signals");
    public static final @NotNull Tag<@NotNull Block> PIGLIN_REPELLENTS = get("piglin_repellents");
    public static final @NotNull Tag<@NotNull Block> PLANKS = get("planks");
    public static final @NotNull Tag<@NotNull Block> PORTALS = get("portals");
    public static final @NotNull Tag<@NotNull Block> PRESSURE_PLATES = get("pressure_plates");
    public static final @NotNull Tag<@NotNull Block> PREVENT_MOB_SPAWNING_INSIDE = get("prevent_mob_spawning_inside");
    public static final @NotNull Tag<@NotNull Block> RAILS = get("rails");
    public static final @NotNull Tag<@NotNull Block> REDSTONE_ORES = get("redstone_ores");
    public static final @NotNull Tag<@NotNull Block> SAND = get("sand");
    public static final @NotNull Tag<@NotNull Block> SAPLINGS = get("saplings");
    public static final @NotNull Tag<@NotNull Block> SHULKER_BOXES = get("shulker_boxes");
    public static final @NotNull Tag<@NotNull Block> SIGNS = get("signs");
    public static final @NotNull Tag<@NotNull Block> SLABS = get("slabs");
    public static final @NotNull Tag<@NotNull Block> SMALL_DRIPLEAF_PLACEABLE = get("small_dripleaf_placeable");
    public static final @NotNull Tag<@NotNull Block> SMALL_FLOWERS = get("small_flowers");
    public static final @NotNull Tag<@NotNull Block> SNOW = get("snow");
    public static final @NotNull Tag<@NotNull Block> SOUL_FIRE_BASE_BLOCKS = get("soul_fire_base_blocks");
    public static final @NotNull Tag<@NotNull Block> SOUL_SPEED_BLOCKS = get("soul_speed_blocks");
    public static final @NotNull Tag<@NotNull Block> SPRUCE_LOGS = get("spruce_logs");
    public static final @NotNull Tag<@NotNull Block> STAIRS = get("stairs");
    public static final @NotNull Tag<@NotNull Block> STANDING_SIGNS = get("standing_signs");
    public static final @NotNull Tag<@NotNull Block> STONE_BRICKS = get("stone_bricks");
    public static final @NotNull Tag<@NotNull Block> STONE_ORE_REPLACEABLES = get("stone_ore_replaceables");
    public static final @NotNull Tag<@NotNull Block> STONE_PRESSURE_PLATES = get("stone_pressure_plates");
    public static final @NotNull Tag<@NotNull Block> STRIDER_WARM_BLOCKS = get("strider_warm_blocks");
    public static final @NotNull Tag<@NotNull Block> TALL_FLOWERS = get("tall_flowers");
    public static final @NotNull Tag<@NotNull Block> TRAPDOORS = get("trapdoors");
    public static final @NotNull Tag<@NotNull Block> UNDERWATER_BONEMEALS = get("underwater_bonemeals");
    public static final @NotNull Tag<@NotNull Block> UNSTABLE_BOTTOM_CENTER = get("unstable_bottom_center");
    public static final @NotNull Tag<@NotNull Block> VALID_SPAWN = get("valid_spawn");
    public static final @NotNull Tag<@NotNull Block> WALLS = get("walls");
    public static final @NotNull Tag<@NotNull Block> WALL_CORALS = get("wall_corals");
    public static final @NotNull Tag<@NotNull Block> WALL_POST_OVERRIDE = get("wall_post_override");
    public static final @NotNull Tag<@NotNull Block> WALL_SIGNS = get("wall_signs");
    public static final @NotNull Tag<@NotNull Block> WARPED_STEMS = get("warped_stems");
    public static final @NotNull Tag<@NotNull Block> WART_BLOCKS = get("wart_blocks");
    public static final @NotNull Tag<@NotNull Block> WITHER_IMMUNE = get("wither_immune");
    public static final @NotNull Tag<@NotNull Block> WITHER_SUMMON_BASE_BLOCKS = get("wither_summon_base_blocks");
    public static final @NotNull Tag<@NotNull Block> WOODEN_BUTTONS = get("wooden_buttons");
    public static final @NotNull Tag<@NotNull Block> WOODEN_DOORS = get("wooden_doors");
    public static final @NotNull Tag<@NotNull Block> WOODEN_FENCES = get("wooden_fences");
    public static final @NotNull Tag<@NotNull Block> WOODEN_PRESSURE_PLATES = get("wooden_pressure_plates");
    public static final @NotNull Tag<@NotNull Block> WOODEN_SLABS = get("wooden_slabs");
    public static final @NotNull Tag<@NotNull Block> WOODEN_STAIRS = get("wooden_stairs");
    public static final @NotNull Tag<@NotNull Block> WOODEN_TRAPDOORS = get("wooden_trapdoors");
    public static final @NotNull Tag<@NotNull Block> WOOL = get("wool");

    private static Tag<Block> get(final String name) {
        return MinecraftServer.getTagManager().get(TagType.BLOCKS, "minecraft:" + name);
    }

    private BlockTags() {
    }
}
