package net.minestom.server.world;

import net.minestom.server.registry.DynamicRegistry;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface DimensionTypes {
    DynamicRegistry.Key<DimensionType> THE_END = DynamicRegistry.Key.of("minecraft:the_end");

    DynamicRegistry.Key<DimensionType> OVERWORLD_CAVES = DynamicRegistry.Key.of("minecraft:overworld_caves");

    DynamicRegistry.Key<DimensionType> THE_NETHER = DynamicRegistry.Key.of("minecraft:the_nether");

    DynamicRegistry.Key<DimensionType> OVERWORLD = DynamicRegistry.Key.of("minecraft:overworld");
}
