package net.minestom.server.recipe;

import net.kyori.adventure.key.Key;
import net.minestom.server.network.NetworkBuffer;
import net.minestom.server.registry.StaticProtocolObject;
import org.jetbrains.annotations.NotNull;

/**
 * AUTOGENERATED by RecipeTypeGenerator
 */
public enum RecipeType implements StaticProtocolObject {
    SHAPED(Key.key("minecraft:crafting_shaped")),

    SHAPELESS(Key.key("minecraft:crafting_shapeless")),

    SPECIAL_ARMORDYE(Key.key("minecraft:crafting_special_armordye")),

    SPECIAL_BOOKCLONING(Key.key("minecraft:crafting_special_bookcloning")),

    SPECIAL_MAPCLONING(Key.key("minecraft:crafting_special_mapcloning")),

    SPECIAL_MAPEXTENDING(Key.key("minecraft:crafting_special_mapextending")),

    SPECIAL_FIREWORK_ROCKET(Key.key("minecraft:crafting_special_firework_rocket")),

    SPECIAL_FIREWORK_STAR(Key.key("minecraft:crafting_special_firework_star")),

    SPECIAL_FIREWORK_STAR_FADE(Key.key("minecraft:crafting_special_firework_star_fade")),

    SPECIAL_TIPPEDARROW(Key.key("minecraft:crafting_special_tippedarrow")),

    SPECIAL_BANNERDUPLICATE(Key.key("minecraft:crafting_special_bannerduplicate")),

    SPECIAL_SHIELDDECORATION(Key.key("minecraft:crafting_special_shielddecoration")),

    SPECIAL_SHULKERBOXCOLORING(Key.key("minecraft:crafting_special_shulkerboxcoloring")),

    SPECIAL_SUSPICIOUSSTEW(Key.key("minecraft:crafting_special_suspiciousstew")),

    SPECIAL_REPAIRITEM(Key.key("minecraft:crafting_special_repairitem")),

    SMELTING(Key.key("minecraft:smelting")),

    BLASTING(Key.key("minecraft:blasting")),

    SMOKING(Key.key("minecraft:smoking")),

    CAMPFIRE_COOKING(Key.key("minecraft:campfire_cooking")),

    STONECUTTING(Key.key("minecraft:stonecutting")),

    SMITHING_TRANSFORM(Key.key("minecraft:smithing_transform")),

    SMITHING_TRIM(Key.key("minecraft:smithing_trim")),

    DECORATED_POT(Key.key("minecraft:crafting_decorated_pot"));

    public static final NetworkBuffer.Type<RecipeType> NETWORK_TYPE = NetworkBuffer.Enum(RecipeType.class);

    private final Key namespace;

    RecipeType(@NotNull Key namespace) {
        this.namespace = namespace;
    }

    @NotNull
    @Override
    public Key namespace() {
        return this.namespace;
    }

    @Override
    public int id() {
        return this.ordinal();
    }
}
