package net.minestom.server.inventory.click;

public enum ClickType {

    LEFT_CLICK,
    RIGHT_CLICK,
    CHANGE_HELD,

    START_LEFT_SHIFT_CLICK,
    START_RIGHT_SHIFT_CLICK,
    SHIFT_LEFT_CLICK,
    SHIFT_RIGHT_CLICK,

    START_LEFT_DRAGGING,
    START_RIGHT_DRAGGING,

    LEFT_DRAGGING,
    RIGHT_DRAGGING,

    END_LEFT_DRAGGING,
    END_RIGHT_DRAGGING,

    START_DOUBLE_CLICK,
    DOUBLE_CLICK,

    DROP

}
