package net.minestom.server.entity;

/**
 * Code autogenerated, do not edit!
 */
@SuppressWarnings("unused")
interface EntityTypes {
    EntityType ALLAY = EntityTypeImpl.get("minecraft:allay");

    EntityType AREA_EFFECT_CLOUD = EntityTypeImpl.get("minecraft:area_effect_cloud");

    EntityType ARMOR_STAND = EntityTypeImpl.get("minecraft:armor_stand");

    EntityType ARROW = EntityTypeImpl.get("minecraft:arrow");

    EntityType AXOLOTL = EntityTypeImpl.get("minecraft:axolotl");

    EntityType BAT = EntityTypeImpl.get("minecraft:bat");

    EntityType BEE = EntityTypeImpl.get("minecraft:bee");

    EntityType BLAZE = EntityTypeImpl.get("minecraft:blaze");

    EntityType BOAT = EntityTypeImpl.get("minecraft:boat");

    EntityType CHEST_BOAT = EntityTypeImpl.get("minecraft:chest_boat");

    EntityType CAT = EntityTypeImpl.get("minecraft:cat");

    EntityType CAVE_SPIDER = EntityTypeImpl.get("minecraft:cave_spider");

    EntityType CHICKEN = EntityTypeImpl.get("minecraft:chicken");

    EntityType COD = EntityTypeImpl.get("minecraft:cod");

    EntityType COW = EntityTypeImpl.get("minecraft:cow");

    EntityType CREEPER = EntityTypeImpl.get("minecraft:creeper");

    EntityType DOLPHIN = EntityTypeImpl.get("minecraft:dolphin");

    EntityType DONKEY = EntityTypeImpl.get("minecraft:donkey");

    EntityType DRAGON_FIREBALL = EntityTypeImpl.get("minecraft:dragon_fireball");

    EntityType DROWNED = EntityTypeImpl.get("minecraft:drowned");

    EntityType ELDER_GUARDIAN = EntityTypeImpl.get("minecraft:elder_guardian");

    EntityType END_CRYSTAL = EntityTypeImpl.get("minecraft:end_crystal");

    EntityType ENDER_DRAGON = EntityTypeImpl.get("minecraft:ender_dragon");

    EntityType ENDERMAN = EntityTypeImpl.get("minecraft:enderman");

    EntityType ENDERMITE = EntityTypeImpl.get("minecraft:endermite");

    EntityType EVOKER = EntityTypeImpl.get("minecraft:evoker");

    EntityType EVOKER_FANGS = EntityTypeImpl.get("minecraft:evoker_fangs");

    EntityType EXPERIENCE_ORB = EntityTypeImpl.get("minecraft:experience_orb");

    EntityType EYE_OF_ENDER = EntityTypeImpl.get("minecraft:eye_of_ender");

    EntityType FALLING_BLOCK = EntityTypeImpl.get("minecraft:falling_block");

    EntityType FIREWORK_ROCKET = EntityTypeImpl.get("minecraft:firework_rocket");

    EntityType FOX = EntityTypeImpl.get("minecraft:fox");

    EntityType FROG = EntityTypeImpl.get("minecraft:frog");

    EntityType GHAST = EntityTypeImpl.get("minecraft:ghast");

    EntityType GIANT = EntityTypeImpl.get("minecraft:giant");

    EntityType GLOW_ITEM_FRAME = EntityTypeImpl.get("minecraft:glow_item_frame");

    EntityType GLOW_SQUID = EntityTypeImpl.get("minecraft:glow_squid");

    EntityType GOAT = EntityTypeImpl.get("minecraft:goat");

    EntityType GUARDIAN = EntityTypeImpl.get("minecraft:guardian");

    EntityType HOGLIN = EntityTypeImpl.get("minecraft:hoglin");

    EntityType HORSE = EntityTypeImpl.get("minecraft:horse");

    EntityType HUSK = EntityTypeImpl.get("minecraft:husk");

    EntityType ILLUSIONER = EntityTypeImpl.get("minecraft:illusioner");

    EntityType IRON_GOLEM = EntityTypeImpl.get("minecraft:iron_golem");

    EntityType ITEM = EntityTypeImpl.get("minecraft:item");

    EntityType ITEM_FRAME = EntityTypeImpl.get("minecraft:item_frame");

    EntityType FIREBALL = EntityTypeImpl.get("minecraft:fireball");

    EntityType LEASH_KNOT = EntityTypeImpl.get("minecraft:leash_knot");

    EntityType LIGHTNING_BOLT = EntityTypeImpl.get("minecraft:lightning_bolt");

    EntityType LLAMA = EntityTypeImpl.get("minecraft:llama");

    EntityType LLAMA_SPIT = EntityTypeImpl.get("minecraft:llama_spit");

    EntityType MAGMA_CUBE = EntityTypeImpl.get("minecraft:magma_cube");

    EntityType MARKER = EntityTypeImpl.get("minecraft:marker");

    EntityType MINECART = EntityTypeImpl.get("minecraft:minecart");

    EntityType CHEST_MINECART = EntityTypeImpl.get("minecraft:chest_minecart");

    EntityType COMMAND_BLOCK_MINECART = EntityTypeImpl.get("minecraft:command_block_minecart");

    EntityType FURNACE_MINECART = EntityTypeImpl.get("minecraft:furnace_minecart");

    EntityType HOPPER_MINECART = EntityTypeImpl.get("minecraft:hopper_minecart");

    EntityType SPAWNER_MINECART = EntityTypeImpl.get("minecraft:spawner_minecart");

    EntityType TNT_MINECART = EntityTypeImpl.get("minecraft:tnt_minecart");

    EntityType MULE = EntityTypeImpl.get("minecraft:mule");

    EntityType MOOSHROOM = EntityTypeImpl.get("minecraft:mooshroom");

    EntityType OCELOT = EntityTypeImpl.get("minecraft:ocelot");

    EntityType PAINTING = EntityTypeImpl.get("minecraft:painting");

    EntityType PANDA = EntityTypeImpl.get("minecraft:panda");

    EntityType PARROT = EntityTypeImpl.get("minecraft:parrot");

    EntityType PHANTOM = EntityTypeImpl.get("minecraft:phantom");

    EntityType PIG = EntityTypeImpl.get("minecraft:pig");

    EntityType PIGLIN = EntityTypeImpl.get("minecraft:piglin");

    EntityType PIGLIN_BRUTE = EntityTypeImpl.get("minecraft:piglin_brute");

    EntityType PILLAGER = EntityTypeImpl.get("minecraft:pillager");

    EntityType POLAR_BEAR = EntityTypeImpl.get("minecraft:polar_bear");

    EntityType TNT = EntityTypeImpl.get("minecraft:tnt");

    EntityType PUFFERFISH = EntityTypeImpl.get("minecraft:pufferfish");

    EntityType RABBIT = EntityTypeImpl.get("minecraft:rabbit");

    EntityType RAVAGER = EntityTypeImpl.get("minecraft:ravager");

    EntityType SALMON = EntityTypeImpl.get("minecraft:salmon");

    EntityType SHEEP = EntityTypeImpl.get("minecraft:sheep");

    EntityType SHULKER = EntityTypeImpl.get("minecraft:shulker");

    EntityType SHULKER_BULLET = EntityTypeImpl.get("minecraft:shulker_bullet");

    EntityType SILVERFISH = EntityTypeImpl.get("minecraft:silverfish");

    EntityType SKELETON = EntityTypeImpl.get("minecraft:skeleton");

    EntityType SKELETON_HORSE = EntityTypeImpl.get("minecraft:skeleton_horse");

    EntityType SLIME = EntityTypeImpl.get("minecraft:slime");

    EntityType SMALL_FIREBALL = EntityTypeImpl.get("minecraft:small_fireball");

    EntityType SNOW_GOLEM = EntityTypeImpl.get("minecraft:snow_golem");

    EntityType SNOWBALL = EntityTypeImpl.get("minecraft:snowball");

    EntityType SPECTRAL_ARROW = EntityTypeImpl.get("minecraft:spectral_arrow");

    EntityType SPIDER = EntityTypeImpl.get("minecraft:spider");

    EntityType SQUID = EntityTypeImpl.get("minecraft:squid");

    EntityType STRAY = EntityTypeImpl.get("minecraft:stray");

    EntityType STRIDER = EntityTypeImpl.get("minecraft:strider");

    EntityType TADPOLE = EntityTypeImpl.get("minecraft:tadpole");

    EntityType EGG = EntityTypeImpl.get("minecraft:egg");

    EntityType ENDER_PEARL = EntityTypeImpl.get("minecraft:ender_pearl");

    EntityType EXPERIENCE_BOTTLE = EntityTypeImpl.get("minecraft:experience_bottle");

    EntityType POTION = EntityTypeImpl.get("minecraft:potion");

    EntityType TRIDENT = EntityTypeImpl.get("minecraft:trident");

    EntityType TRADER_LLAMA = EntityTypeImpl.get("minecraft:trader_llama");

    EntityType TROPICAL_FISH = EntityTypeImpl.get("minecraft:tropical_fish");

    EntityType TURTLE = EntityTypeImpl.get("minecraft:turtle");

    EntityType VEX = EntityTypeImpl.get("minecraft:vex");

    EntityType VILLAGER = EntityTypeImpl.get("minecraft:villager");

    EntityType VINDICATOR = EntityTypeImpl.get("minecraft:vindicator");

    EntityType WANDERING_TRADER = EntityTypeImpl.get("minecraft:wandering_trader");

    EntityType WARDEN = EntityTypeImpl.get("minecraft:warden");

    EntityType WITCH = EntityTypeImpl.get("minecraft:witch");

    EntityType WITHER = EntityTypeImpl.get("minecraft:wither");

    EntityType WITHER_SKELETON = EntityTypeImpl.get("minecraft:wither_skeleton");

    EntityType WITHER_SKULL = EntityTypeImpl.get("minecraft:wither_skull");

    EntityType WOLF = EntityTypeImpl.get("minecraft:wolf");

    EntityType ZOGLIN = EntityTypeImpl.get("minecraft:zoglin");

    EntityType ZOMBIE = EntityTypeImpl.get("minecraft:zombie");

    EntityType ZOMBIE_HORSE = EntityTypeImpl.get("minecraft:zombie_horse");

    EntityType ZOMBIE_VILLAGER = EntityTypeImpl.get("minecraft:zombie_villager");

    EntityType ZOMBIFIED_PIGLIN = EntityTypeImpl.get("minecraft:zombified_piglin");

    EntityType PLAYER = EntityTypeImpl.get("minecraft:player");

    EntityType FISHING_BOBBER = EntityTypeImpl.get("minecraft:fishing_bobber");
}
