name: Build
on:
  push:
    branches:
      - master
jobs:
  Build:
    name: Build and Publish
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - id: vars
        run: echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT
      - name: Publish to Central via Build
        if: github.repository_owner == 'Minestom'
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
          echo "Version: ${MINESTOM_VERSION}" >> $GITHUB_STEP_SUMMARY
        env:
          MINESTOM_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
          MINESTOM_CHANNEL: release
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}