name: Build and deploy Javadoc

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build javadoc
      run: ./gradlew javadoc
      
    - name: Deploy javadoc to its assigned branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: javadoc
        FOLDER: build/docs/javadoc
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ".github/javadoc-publish-clear"
