package net.minestom.server.instance.block.property.enums;

import java.lang.Override;
import java.lang.String;
import net.minestom.server.instance.block.property.PropertyEnum;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * AUTOGENERATED by PropertyGenerator
 */
public enum CreakingHeartState implements PropertyEnum {
    UPROOTED,

    DORMANT,

    AWAKE;

    @Override
    @NotNull
    public String property() {
        return "creaking_heart_state";
    }

    @Override
    @NotNull
    public String untypedValue() {
        return switch (this) {
            case UPROOTED -> "uprooted";
            case DORMANT -> "dormant";
            case AWAKE -> "awake";
        };
    }

    @Nullable
    public static CreakingHeartState typedValueOf(String value) {
        return switch (value) {
            case "uprooted" -> UPROOTED;
            case "dormant" -> DORMANT;
            case "awake" -> AWAKE;
            default -> null;
        };
    }
}
