package net.minestom.server.instance.block.property.enums;

import java.lang.Override;
import java.lang.String;
import net.minestom.server.instance.block.property.PropertyEnum;
import org.jetbrains.annotations.Nullable;

/**
 * AUTOGENERATED by PropertyGenerator
 */
public enum Facing implements PropertyEnum.Keyed {
    NORTH,

    EAST,

    SOUTH,

    WEST,

    UP,

    DOWN;

    @Override
    public String key() {
        return "facing";
    }

    @Override
    public String value() {
        return switch (this) {
            case NORTH -> "north";
            case EAST -> "east";
            case SOUTH -> "south";
            case WEST -> "west";
            case UP -> "up";
            case DOWN -> "down";
        };
    }

    @Nullable
    public static Facing parse(String value) {
        return switch (value) {
            case "north" -> NORTH;
            case "east" -> EAST;
            case "south" -> SOUTH;
            case "west" -> WEST;
            case "up" -> UP;
            case "down" -> DOWN;
            default -> null;
        };
    }
}
