package net.minestom.server.instance.block.property.enums;

import java.lang.Override;
import java.lang.String;
import net.minestom.server.instance.block.property.PropertyEnum;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * AUTOGENERATED by PropertyGenerator
 */
public enum PointedDripstoneVerticalDirection implements PropertyEnum {
    UP,

    DOWN;

    @Override
    @NotNull
    public String property() {
        return "vertical_direction";
    }

    @Override
    @NotNull
    public String untypedValue() {
        return switch (this) {
            case UP -> "up";
            case DOWN -> "down";
        };
    }

    @Nullable
    public static PointedDripstoneVerticalDirection typedValueOf(String value) {
        return switch (value) {
            case "up" -> UP;
            case "down" -> DOWN;
            default -> null;
        };
    }
}
