package net.minestom.server.instance.block.property.enums;

import java.lang.Override;
import java.lang.String;
import net.minestom.server.instance.block.property.PropertyEnum;
import org.jetbrains.annotations.Nullable;

/**
 * AUTOGENERATED by PropertyGenerator
 */
public enum SculkSensorPhase implements PropertyEnum.Keyed {
    INACTIVE,

    ACTIVE,

    COOLDOWN;

    @Override
    public String key() {
        return "sculk_sensor_phase";
    }

    @Override
    public String value() {
        return switch (this) {
            case INACTIVE -> "inactive";
            case ACTIVE -> "active";
            case COOLDOWN -> "cooldown";
        };
    }

    @Nullable
    public static SculkSensorPhase parse(String value) {
        return switch (value) {
            case "inactive" -> INACTIVE;
            case "active" -> ACTIVE;
            case "cooldown" -> COOLDOWN;
            default -> null;
        };
    }
}
