package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class DioriteStairs {
	public static void initStates() {
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10173, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10174, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10175, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10176, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10177, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10178, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10179, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10180, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10181, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10182, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10183, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10184, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10185, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10186, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10187, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10188, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10189, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10190, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10191, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10192, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10193, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10194, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10195, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10196, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10197, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10198, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10199, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10200, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10201, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10202, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10203, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10204, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10205, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10206, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10207, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10208, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10209, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10210, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10211, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10212, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10213, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10214, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10215, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10216, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10217, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10218, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10219, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10220, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10221, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10222, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10223, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10224, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10225, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10226, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10227, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10228, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10229, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10230, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10231, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10232, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10233, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10234, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10235, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10236, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10237, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10238, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10239, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10240, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10241, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10242, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10243, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10244, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10245, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10246, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10247, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10248, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10249, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10250, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10251, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		DIORITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 10252, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
