package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class GraniteStairs {
	public static void initStates() {
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9853, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9854, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9855, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9856, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9857, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9858, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9859, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9860, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9861, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9862, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9863, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9864, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9865, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9866, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9867, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9868, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9869, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9870, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9871, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9872, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9873, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9874, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9875, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9876, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9877, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9878, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9879, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9880, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9881, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9882, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9883, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9884, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9885, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9886, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9887, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9888, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9889, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9890, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9891, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9892, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9893, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9894, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9895, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9896, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9897, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9898, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9899, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9900, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9901, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9902, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9903, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9904, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9905, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9906, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9907, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9908, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9909, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9910, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9911, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9912, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9913, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9914, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9915, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9916, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9917, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9918, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9919, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9920, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9921, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9922, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9923, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9924, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9925, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9926, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9927, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9928, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9929, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9930, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9931, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		GRANITE_STAIRS.addBlockAlternative(new BlockAlternative((short) 9932, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
