package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class MossyStoneBrickStairs {
	public static void initStates() {
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9293, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9294, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9295, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9296, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9297, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9298, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9299, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9300, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9301, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9302, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9303, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9304, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9305, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9306, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9307, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9308, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9309, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9310, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9311, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9312, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9313, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9314, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9315, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9316, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9317, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9318, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9319, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9320, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9321, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9322, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9323, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9324, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9325, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9326, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9327, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9328, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9329, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9330, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9331, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9332, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9333, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9334, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9335, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9336, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9337, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9338, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9339, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9340, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9341, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9342, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9343, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9344, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9345, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9346, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9347, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9348, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9349, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9350, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9351, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9352, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9353, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9354, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9355, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9356, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9357, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9358, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9359, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9360, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9361, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9362, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9363, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9364, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9365, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9366, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9367, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9368, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9369, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9370, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9371, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		MOSSY_STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 9372, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
