package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class NetherBrickStairs {
	public static void initStates() {
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5032, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5033, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5034, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5035, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5036, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5037, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5038, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5039, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5040, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5041, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5042, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5043, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5044, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5045, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5046, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5047, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5048, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5049, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5050, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5051, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5052, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5053, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5054, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5055, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5056, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5057, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5058, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5059, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5060, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5061, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5062, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5063, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5064, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5065, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5066, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5067, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5068, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5069, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5070, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5071, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5072, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5073, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5074, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5075, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5076, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5077, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5078, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5079, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5080, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5081, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5082, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5083, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5084, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5085, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5086, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5087, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5088, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5089, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5090, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5091, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5092, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5093, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5094, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5095, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5096, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5097, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5098, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5099, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5100, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5101, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5102, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5103, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5104, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5105, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5106, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5107, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5108, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5109, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5110, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		NETHER_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 5111, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
