package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class PrismarineStairs {
	public static void initStates() {
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7068, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7069, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7070, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7071, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7072, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7073, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7074, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7075, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7076, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7077, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7078, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7079, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7080, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7081, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7082, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7083, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7084, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7085, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7086, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7087, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7088, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7089, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7090, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7091, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7092, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7093, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7094, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7095, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7096, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7097, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7098, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7099, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7100, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7101, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7102, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7103, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7104, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7105, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7106, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7107, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7108, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7109, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7110, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7111, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7112, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7113, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7114, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7115, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7116, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7117, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7118, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7119, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7120, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7121, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7122, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7123, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7124, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7125, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7126, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7127, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7128, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7129, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7130, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7131, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7132, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7133, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7134, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7135, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7136, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7137, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7138, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7139, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7140, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7141, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7142, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7143, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7144, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7145, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7146, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		PRISMARINE_STAIRS.addBlockAlternative(new BlockAlternative((short) 7147, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
