package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class QuartzStairs {
	public static void initStates() {
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6207, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6208, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6209, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6210, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6211, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6212, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6213, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6214, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6215, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6216, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6217, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6218, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6219, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6220, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6221, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6222, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6223, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6224, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6225, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6226, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6227, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6228, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6229, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6230, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6231, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6232, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6233, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6234, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6235, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6236, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6237, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6238, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6239, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6240, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6241, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6242, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6243, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6244, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6245, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6246, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6247, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6248, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6249, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6250, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6251, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6252, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6253, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6254, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6255, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6256, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6257, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6258, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6259, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6260, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6261, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6262, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6263, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6264, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6265, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6266, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6267, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6268, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6269, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6270, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6271, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6272, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6273, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6274, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6275, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6276, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6277, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6278, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6279, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6280, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6281, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6282, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6283, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6284, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6285, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		QUARTZ_STAIRS.addBlockAlternative(new BlockAlternative((short) 6286, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
