package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class SandstoneStairs {
	public static void initStates() {
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5154, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5155, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5156, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5157, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5158, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5159, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5160, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5161, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5162, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5163, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5164, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5165, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5166, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5167, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5168, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5169, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5170, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5171, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5172, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5173, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5174, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5175, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5176, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5177, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5178, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5179, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5180, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5181, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5182, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5183, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5184, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5185, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5186, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5187, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5188, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5189, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5190, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5191, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5192, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5193, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5194, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5195, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5196, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5197, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5198, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5199, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5200, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5201, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5202, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5203, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5204, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5205, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5206, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5207, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5208, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5209, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5210, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5211, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5212, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5213, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5214, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5215, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5216, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5217, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5218, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5219, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5220, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5221, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5222, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5223, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5224, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5225, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5226, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5227, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5228, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5229, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5230, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5231, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5232, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		SANDSTONE_STAIRS.addBlockAlternative(new BlockAlternative((short) 5233, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
