package net.minestom.instance.block.states;
import net.minestom.server.instance.block.BlockAlternative;
import static net.minestom.instance.block.TmpBlock.*;
/**
 * Completely internal. DO NOT USE. IF YOU ARE A USER AND FACE A PROBLEM WHILE USING THIS CODE, THAT'S ON YOU.
 */
@Deprecated(forRemoval = false, since = "forever")
public class StoneBrickStairs {
	public static void initStates() {
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4916, "facing=north", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4917, "facing=north", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4918, "facing=north", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4919, "facing=north", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4920, "facing=north", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4921, "facing=north", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4922, "facing=north", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4923, "facing=north", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4924, "facing=north", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4925, "facing=north", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4926, "facing=north", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4927, "facing=north", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4928, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4929, "facing=north", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4930, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4931, "facing=north", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4932, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4933, "facing=north", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4934, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4935, "facing=north", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4936, "facing=south", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4937, "facing=south", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4938, "facing=south", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4939, "facing=south", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4940, "facing=south", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4941, "facing=south", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4942, "facing=south", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4943, "facing=south", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4944, "facing=south", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4945, "facing=south", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4946, "facing=south", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4947, "facing=south", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4948, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4949, "facing=south", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4950, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4951, "facing=south", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4952, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4953, "facing=south", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4954, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4955, "facing=south", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4956, "facing=west", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4957, "facing=west", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4958, "facing=west", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4959, "facing=west", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4960, "facing=west", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4961, "facing=west", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4962, "facing=west", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4963, "facing=west", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4964, "facing=west", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4965, "facing=west", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4966, "facing=west", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4967, "facing=west", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4968, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4969, "facing=west", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4970, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4971, "facing=west", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4972, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4973, "facing=west", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4974, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4975, "facing=west", "half=bottom", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4976, "facing=east", "half=top", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4977, "facing=east", "half=top", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4978, "facing=east", "half=top", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4979, "facing=east", "half=top", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4980, "facing=east", "half=top", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4981, "facing=east", "half=top", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4982, "facing=east", "half=top", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4983, "facing=east", "half=top", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4984, "facing=east", "half=top", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4985, "facing=east", "half=top", "shape=outer_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4986, "facing=east", "half=bottom", "shape=straight", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4987, "facing=east", "half=bottom", "shape=straight", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4988, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4989, "facing=east", "half=bottom", "shape=inner_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4990, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4991, "facing=east", "half=bottom", "shape=inner_right", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4992, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4993, "facing=east", "half=bottom", "shape=outer_left", "waterlogged=false"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4994, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=true"));
		STONE_BRICK_STAIRS.addBlockAlternative(new BlockAlternative((short) 4995, "facing=east", "half=bottom", "shape=outer_right", "waterlogged=false"));
	}
}
